### ISSUE TITLE
Rubix cache did not work？

### ISSUE THREAD

**Issue by ImTangYun** [trinodb/trino#10126]
When I add config to hive connector as below：

    connector.name=hive
    hive.cache.enabled=true
    hive.cache.location=/opt/hive-cache
 
When I execute some query，i didnt found cache directory ‘/opt/hive-cache’ on my server
Anyone met the same problem？

**Comment by tayarajat** [comment]
The caching directory should be **present on all the worker nodes before** starting the trino-server. 
Otherwise you must be getting the below error in your worker logs:
` ERROR   main    com.qubole.rubix.bookkeeper.BookKeeperServer    Cache directories could not be created
java.io.FileNotFoundException: None of the cache parent directories exists`

**Comment by hashhar** [comment]
Closing since @tayarajat has provided a solution. Feel free to reopen or continue discussion on Slack if this doesn't help your case.
