### ISSUE TITLE
Error when trying to 'launcher run'

### ISSUE THREAD

**Issue by JeevansSP** [trinodb/trino#10431]
[https://towardsdatascience.com/getting-started-with-trino-query-engine-dc6a2d027d5](url)
i followed this guide and set everything up but when I go to bin and execute launcher run I get the following error 
**'launcher' is not recognized as an internal or external command,
operable program or batch file.** 

now if I give the full directory and try to run it I get the following error 

**'C:\trino\trino-server-366\bin\launcher' is not recognized as an internal or external command,
operable program or batch file.**

please help

**Comment by findinpath** [comment]
@JeevansSP  this is happening because you are trying to start Trino in Windows which is _currently_ not a supported operated system.

If you have however docker on your machine, you could use

```
docker run --rm -d --name trino -p 8080:8080 trinodb/trino
```

to get started with Trino and 

```
docker container exec -it trino  trino
```

to connect to Trino via the Trino CLI tool.

**Comment by hashhar** [comment]
Thanks @findinpath for helping out. Indeed Trino server cannot be run on Windows. However you can run the server inside Docker containers or on Linux and still use Trino-CLI from Windows to connect to it.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there. We try to keep the GitHub issues focused on bugs instead of troubleshooting.
