### ISSUE TITLE
Metadata caching may return incorrect data

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#10512]
Guava cache that we are using for metadata caching in many places (like hive metastore caching or JDBC connector metadata caching) is vulnerable to: https://github.com/google/guava/issues/1881

The issue is causing that cache entry invalidation does not cancel (invalidate) the existing load execution and that could lead to stale data being loaded. This may lead to incorrect results.

**Comment by kokosing** [comment]
The issue can be reproduced with: https://github.com/trinodb/trino/pull/10513

I tried to play with caffeine (as Internet suggested) to see if it helps, however it was still failing. And javadoc says behavior in such case is undefined: https://github.com/ben-manes/caffeine/blob/5e834f8fdcf3819a242da7a44d7e62c7fde0ab2a/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L174

**Comment by ben-manes** [comment]
Unfortunately this is a limitation due to decorating `ConcurrentHashMap`, because an iterator skips over in-flight computations. It's `clear()` method will block if it traverses over a pending load, but the externalized iterators do not. As the cache has to maintain additional metadata and functionality it has to know which entry was removed (e.g. to notify a removal listener).

A possible workaround is to use `AsyncCache` which stores a mapping to a `CompletableFuture<V>`. This way the map operation is immediate as the expensive computation is performed outside of its locks. This would load on a background thread, though you can have a caller-runs policy by using the classic putIfAbsent-style [memoization](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) (ala JCIP).

Another approach that is implementation agnostic is to use a generation id as part of the cache key. By simply incrementing the counter, the old entries cannot be queried for and will eventually be evicted. This is somewhat common for remote caches like memcached / redis. Ideally you might proactively discard existing entries so that only an in-flight load is retained. If those stragglers are a problem then the caller could validate that the entry is still part of the current generation and discard + retry if not. This strategy is likely the best as very explicit and easily understood in code, since you'll want to document that assertion to avoid future regressions.

**Comment by kokosing** [comment]
The idea with generation id is really nice. However, it won't fly with guava cache as we also call invalidate per cache key. So we would need to do switch to Caffeinate or fix guava cache.

**Comment by kokosing** [comment]
Also methods like `io.trino.plugin.jdbc.CachingJdbcClient#invalidateCache` have no chance to invalidate entries that are during load (or reload).

**Comment by ben-manes** [comment]
Oh sorry, the reference to `invalidateAll()` led me to assume you were concerned about `CachingJdbcClient.flushCache()`. The per-key linearization should be supported and passes a [linearization test](https://github.com/ben-manes/caffeine/blob/5e834f8fdcf3819a242da7a44d7e62c7fde0ab2a/caffeine/src/test/java/com/github/benmanes/caffeine/cache/testing/AbstractLincheckMapTest.java#L84-L87) (via [Lincheck](https://github.com/Kotlin/kotlinx-lincheck)). In Caffeine a load delegates to `Map.computeIfAbsent` and an invalidate to `Map.remove`, so those cases are covered. The `AsyncCache` trick would be necessary for `invalidateCache` usage to inspect an in-flight load, and that has different linearization semantics (likely acceptable, but different).

**Comment by kokosing** [comment]
Thanks @ben-manes !

My raw current suggestion to solve this issue is:
 - use Caffeine, I do not think that we should fix or wait for the fix in Guava cache
 - use generation id for invalidateAll() use case
 - considering using `AsyncCache` for `invalidateCache`, or consider removing `invalidateCache` method at all (not sure if it is possible). Anyway it is a major refactor.
 - write concurrency tests for each entity that we cache in JDBC connector
 - repeat the exercise for other places where we cache.
 
 This all sounds like a lot of work.

**Comment by ben-manes** [comment]
If you use AsyncCache for invalidateCache then you likely won’t need the generational id trick. The creation of the entry will be immediate so a race will likely be rare / acceptable.

I’d assume most cases where you cache don’t need these workarounds as they are not relying on the linearizability of bulk operations.

**Comment by kokosing** [comment]
> If you use AsyncCache for invalidateCache then you likely won’t need the generational id trick. The creation of the entry will be immediate so a race will likely be rare / acceptable.

Yes. Thanks!

Currently @findepi is pursuing of implementing "AsyncCache" on top of guava cache. Which we could then reuse in the codebase.

**Comment by ben-manes** [comment]
Sounds good. If the future is inserted before its work is started then I think no race can occur, assuming that any shared state is read after that barrier. It's only a race if the future is fired off in parallel, e.g. via a load / compute, as that leaves a tiny time window (such as a context switch). Note that since Guava isn't aware of futures so you might have subtle quirks when it evicts an the entry that is still in-flight or skewed stats.

Out of curiosity, why do you prefer to continue on Guava?

**Comment by findepi** [comment]
> Currently @findepi is pursuing the idea of implementing "AsyncCache" on top of guava cache. Which we could then reuse in the codebase.

This is now merged in https://github.com/trinodb/trino/pull/10544 as `EvictableCache`: https://github.com/trinodb/trino/blob/341cc5a84edbad5b72a4aacc7468c4afd6fe732c/lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/cache/EvictableCache.java

**Comment by kokosing** [comment]
> Out of curiosity, why do you prefer to continue on Guava?

Few random thoughts why we are not migrate to Caffeine (at least why not yet):
 - Caffeine does not solve the problem fully for us. We still need to handle `invalidateAll()` anyway. So migration is out of the scope here.
 - One change at a time. Changing caching implementation will surely affect users somehow. So we prefer to avoid changing cache backend now to make sure that we are able do diagnose issues in future. Once we get sure that current fix is working as expected we might consider changing the backend.
  - I am not sure how to benchmark cost and benefit tradeoffs for Guava cache vs Caffeine.
  - We are concerned a bit about project future. Guava is supported by giant company so future sounds a bit safer here. On the other hand I am disappointed that they haven't fixed/addressed the long standing serious issue.

**Comment by kokosing** [comment]
@findepi Are you going to handle HMS caching too?

**Comment by ben-manes** [comment]
Oh, you're probably only going to get help / support from me regardless. I'll report or fix bugs in Guava as time & interest allows, but I am not very active there. Google internally switched over and the latest JavaDocs for [CacheBuilder](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/cache/CacheBuilder.html) are fairly explicit. While I haven't been at Google since 2012 back when working on the cache as a 20% project, I do retain a good relationship with those Googlers. I'll still provide advice if asked, but I won't set expectations for development support of that code base.

**Comment by ksobolew** [comment]
> Prefer Caffeine over Guava's caching API

I admit I LOL'd when I saw that :) (Also a proof that nobody reads javadocs!)

So it appears that Guava Cache is effectively unmaintained (or abandonware). That's good to know, thanks!

**Comment by kokosing** [comment]
> Caffeine does not solve the problem fully for us. We still need to handle invalidateAll() anyway. So migration is out of the scope here.

@ben-manes Would you like to fix this in Caffeine? Or would you like to accept if we would contribute #10544 to Caffeine?

**Comment by ben-manes** [comment]
It's not a simple fix and would require forking `ConcurrentHashMap` to access internal state (see it's `clear()` implementation). We would need a `forEach` that is linearizable with pending inserts, whereas the Map iterators make no consistency guarantees for inserts after the iterator's construction. A computeIfAbsent style call is not an insert until it completes, so the iterator do honor their contract which is too weak for a linearizable `clear()`.

The JCIP style memoization with a future is the simplest workaround, since you can establish the mapping first and launch the computation afterwards. Since we have async support this is a simplified version of your current fix. Given the stronger consistency requirements this makes the most sense to have to handle yourself.

Even if we forked the hash table, your [invalidateCache(predicate)](https://github.com/trinodb/trino/blob/8cf91f3fd6d567a5cca1160e52dcea8cff02c55b/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java#L553-L560) is not linearizable. It too iterates to find matching keys, which causes it to skip in-flight loads. This would mean you need a linearizable `removeIf` or the ability to inspect an in-flight key. The latter is possible with a future value.

I think the JCIP-style future solution is the best option. Anything further requires changes to `ConcurrentHashMap`, and you are welcome to engage with Doug Lea about that.

**Comment by findepi** [comment]
@ben-manes i took another look at Caffeine to see what use-cases it solves out of the box, i.e. where we do not need our wrapper classes added recently (`EvictableCache`, `EvictableLoadingCache`).

I wrote a covering Guava invalidation issue, `io.trino.plugin.base.cache.TestEvictableCache#testInvalidateOngoingLoad`
https://github.com/trinodb/trino/blob/62efc2c4264c7ef551e67447b3b9c6e206dd8dd8/lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/cache/TestEvictableCache.java#L96-L155

The test has a data provider, and covers 4 different ways to call invalidation.

- for `EvictableCache` is **passes** (obviously, the CI would be red otherwise)
- for Guava cache (`CacheBuilder.newBuilder().build()`) it **fails** each time, with `get`-after-`invalidate` returning a stale value
- for Caffeine (`Caffeine.newBuilder().build()` + some API adjustments) it **fails** for `INVALIDATE_SELECTED_KEYS` mode (the `asMap().keySet()` doesn't seem to return a key for ongoing load) and **times out** for 3 other times. The invalidation is blocked by ongoing load.

I am surprised to see that invalidation is blocking. 
I am also sad that invalidation cannot see keys which are not fully loaded yet.

In Trino, we don't want cache invalidation to be blocking, and we sometimes need to invalidate more than just one given key (`asMap().keySet().stream().filter(...)`), which with blocking cache could lead to block amplification. 

cc @cpovirk if you want to mention blocking in `com.google.common.cache.CacheBuilder` javadoc section about migration to `Caffeine`.

cc @losipiuk

**Comment by ben-manes** [comment]
As stated before, ongoing loads are suppressed by `ConcurrentHashMap` and its iterators. This is the behavior that you will observe when using it directly, as its iterators are defined to only guarantee visibility of entries inserted after the iterator's construction. A `computeIfAbsent` is not visible until after it completes, so the `keySet()` will not return unestablished mappings. A change to this behavior or additional visibility would require that you engage with Doug Lea.

The writes to `ConcurrentHashMap` are linearizable, which is a characteristic that you were befuddled by Guava's lack of with respect to in-flight loads. By being linearizable this requires blocking other writers to the hash table entry, such as `remove(key)` during a `computeIfAbsent`. Caffeine maintains this except for `Map.clear()`, as the bulk operation cannot be linearizable due to the above mentioned suppression of in-flight entries. That can only be done if having access to the internals like `ConcurrentHashMap.clear()` does.

To provide the semantics that you want requires decoupling the computation from the hash table operation. `AsyncCache` does this, thanks to being a `Map<K, CompletableFuture<V>>`. This allows you to maintain linearizability for hash table operations, inspect in-flight loads, and perform operations without blocking on the load until it completes. You took my suggestion by writing `EvictableCache` and confirmed it solved your problem. `Caffeine.buildAsync` provides this abstraction and is comparable, as previously discussed.

Please be aware that your team/project has exhausted my willingness to provide continued support. It is disrespectful to ask for my help, follow my advice, not show gratitude for the assistance, disregard my explanations on why things work a certain way, diminish my work as disappointing and not up to the caliber that your team expects, and seek what you think is a higher authority to highlight the perceived deficiencies. That comes across as not engaging with me, but rather exploitative and feels like an attempt at belittling. As your project is relying on work that I coauthored regardless, the only effect is a lack of my support for your team's future needs. As such, you are welcome to continue to use my work but do not expect me to communicate with your team going forward.

**Comment by findepi** [comment]
> Please be aware that your team/project has exhausted my willingness to provide continued support. It is disrespectful to ask for my help and then follow my advice without showing gratitude for the assistance

That's not exactly what happened. I arguably showed disrespect by not reading your earlier comments closely, and thus EvictableCache is arguably my  own work. 

> To provide the semantics that you want requires decoupling the computation from the hash table operation. AsyncCache does this

I imagine. Yet there is a  trade-off -- requiring caller to deal with a future.
Sounds like `AsyncCache#synchronous` removes this limitation, but in turn it doesn't show ongoing loads among keys (per javadoc). So indeed, we could use `AsyncCache` for invalidation, and `AsyncCache#synchronous` for reads. 
Would that work?

> As such, you are welcome to continue to use my work but do not expect me to communicate with your team going forward.

It sounds like my words upset you. While i fully respect your decision not to communicate with myself, please be so kind and not treat others on the team the same. They did nothing wrong.

**Comment by ben-manes** [comment]
> I imagine. Yet there is a trade-off -- requiring caller to deal with a future.
Sounds like AsyncCache#synchronous removes this limitation, but in turn it doesn't show ongoing loads among keys (per javadoc). So indeed, we could use AsyncCache for invalidation, and AsyncCache#synchronous for reads.
Would that work?

Yes, I believe it would. The `synchronous()` view is not as strict so some details like in-flight loads can leak into the `keySet()` view, etc. and it tries to only block outside of the hash table (which causes different but compatible behavior to the natively synchronous cache). It is therefore best-effort as one might expect from an underlying async cache, which is probably what you want but please do not expect identical semantics.
