### ISSUE TITLE
Tune batch size for partitionNameBatch in GlueHiveMetastore

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#10666]
Currently the GlueHiveMetastore calls

https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-partitions.html#aws-glue-api-catalog-partitions-BatchGetPartition

with a batch of up to `1000` entries.

See https://github.com/trinodb/trino/blob/97b33daccb967ede0ec14c473820464420c1f122/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java#L165

Make this value configurable.

**Comment by findepi** [comment]
when one would want to set this?

**Comment by findinpath** [comment]
One scenario where this setting would come in handy is when dealing with very wide tables (that contain hundreds/thousands of columns).
When asking from https://docs.aws.amazon.com/cli/latest/reference/glue/batch-get-partition.html to deliver information about `1000` partitions, we get in the `StorageDescriptor.Columns` part of the response for each partition the columns of the table and their type.

The response in case of dealing with a table of `3000` columns coming from the API can get (if converted to JSON) up to `60MB` and this corresponds only for about `160` entries out of `800` (the rest are returned by the API in the `UnprocessedKeys` part of the response).

Being able to configure the amount of partitions to ask for from AWS Glue API allows the caller to  batch the partition names to be retrieved in smaller chunks in such exotic cases.

**Comment by hashhar** [comment]
> avoid dealing with custom logic for retrying

This would be a very manual activity. And you cannot know ahead of time what value should you use - so you ideally still want the logic to retry the `UnprocessedKeys`.
It also has the drawback that for non-wide tables performance would suffer.

I believe we should do https://github.com/trinodb/trino/pull/10696 instead since that doesn't require manual tuning and doesn't affect non-wide tables.

**Comment by findinpath** [comment]
> I believe we should do [#10696 ](https://github.com/trinodb/trino/pull/10696)

I agree that this functionality should be implemented.

I was only thinking that being able to tune manually the chunk size would avoid going too many times through the loop of processing the `UnprocessedKeys`.

**Comment by findepi** [comment]
> I was only thinking that being able to tune manually the chunk size would avoid going too many times through the loop of processing the `UnprocessedKeys`.

Good idea. If this **REALLY** is a problem to address, then `io.trino.plugin.hive.metastore.glue.GlueHiveMetastore#batchGetPartition` could choose batch size using a heuristic (it knows the "width" of the table), or adaptively (trying to learn the right batch size based on number of unprocessed keys returned from Glue service).

**Comment by findinpath** [comment]
I realise now that my initial intent of providing bluntly a value for the batch size was rather naive.
It may be that a table is very wide and needs a smaller batch size, but all the other tables are "normal" and they would therefore benefit of a higher value for the chunk size. 
Very likely some heuristic/adaptive approach for the specific case of dealing with `UnprocessedKeys` would be the way to go. I'm reopening the issue because in the light of this new information it may have a chance of being implemented.

**Comment by findepi** [comment]
@findinpath what about

> If this REALLY is a problem to address, ...

do you know the answer?

**Comment by findinpath** [comment]
No, I don't think this is actually a problem to address at the moment. I'm looking forward for the solution coming with #10696

**Comment by cactauz** [comment]
I am late looking at this again but I believe there is still a benefit to implementing this, in the case where we know that 1000 partitions cannot be retrieved in one request.  If we knew a batch size of 50 would succeed without resulting in UnprocessedKeys, then a batch size of 50 would allow multiple batches to be retrieved in parallel (although this may cause new problems with the glue API).  I don't think making this value configurable with a default of the current value of 1000 would not cause any new performance problems.

**Comment by findepi** [comment]
> in the case where we know that 1000 partitions cannot be retrieved in one request. If we knew a batch size of 50 would succeed without resulting in UnprocessedKeys, then a batch size of 50 would allow multiple batches to be retrieved in parallel (although this may cause new problems with the glue API).

i agree

> Ideally it would be configurable per table

i agree -- we currently believe the optimal batch size depends on "table width" (whatever this means precisely), e.g. it's more likely to get UnprocessedKeys on a table with high number of columns

@cactauz the question would be: "under what circumstances would the user set it?"

for example, if the user/sysadmin logic is eventually going to be "tune this down for tables with over 1000 columns", we could implement just that in the code, without a toggle.

**Comment by cactauz** [comment]
> @cactauz the question would be: "under what circumstances would the user set it?"

In my particular situation, where the partitions all have 17000 identical columns, I've observed that the API will always consistently return 17 partitions from batchGetPartitions, and any others will be UnprocessedKeys.

It would be nice to know what exactly the rules are for the glue API to be able to understand how to tune these requests better, but in cases like mine where this consistent type of behavior it would be helpful to configure the value.

**Comment by findepi** [comment]
so we have data points
- 10 columns: 1000 batch is fine
- 17000 columns: 17 batch is fine

assuming this is data size based, we could have a logic like
```
256000 / #columns, but not more than 1000 and not less than 10
```

maybe worth having more experimentation data points first though.

cc @jackye1995 @pettyjamesm

**Comment by pettyjamesm** [comment]
> It would be nice to know what exactly the rules are for the glue API to be able to understand how to tune these requests better, but in cases like mine where this consistent type of behavior has been observed it would be helpful to configure the value.

As far as I know, the reason that the "unprocessed keys" mechanism exists is to protect the systems involved from issues that that can be caused by handling huge payloads, whether that's in the underlying data storage system, the API endpoint, or even the API client. Regardless of what mechanisms or heuristics Glue uses to determine the cut-off threshold today, they are certainly subject to change and logic to handle unprocessed keys remains necessary.

So it seems like the options available are:
1. Require clients to pass a session property override to configure the batch size (note: this unfortunately would not be flexible enough to target a specific table)
2. Use a heuristic to attempt to guess what an appropriate batch size would be based on, eg: table column count
3. Adaptively grow and shrink the current the batch size based on whether unprocessed keys are received

None of the above options are necessarily mutually exclusive, but given that approach 1 can't express different values for different tables easily it seems like a mix of approach 2 and 3 makes the most sense, maybe with approach 1 as a final override on the dynamic behavior if needed.

For approach 2, column count seems like a reasonable parameter to drive the initial batch size estimate, assuming the heuristic is based on a response size limit (note: this is a guess on my part, I have no specific knowledge of how that logic works), other factors like column name lengths and partition metadata size would also be a factor- so incorporating aspects from item 3 would still need to serve as a complement.

**Comment by raunaqmorarka** [comment]
One thing missing from this discussion is that the partitions batch size is not entirely upto the metastore specific logic.
We have code at https://github.com/trinodb/trino/blob/012cd0252aa0dcbea16393096734fff653f6d388/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java#L325 which slices up the partition names list into batch sizes that ramp up exponentially from `hive.metastore.partition-batch-size.min` (default 10) to `hive.metastore.partition-batch-size.max` (default 100). So the metastore specific logic never sees more than `hive.metastore.partition-batch-size.max` partitions in a batched getPartitionsByNames call.
It is generally a good idea to start with small batches for listing partitions metadata because this info is needed to feed the splits generation process which runs asynchronously to splits processing on workers. So we should produce something as soon as possible to start utilizing workers rather than optimizing only for the overall latency of fetching partitions metadata.
