### ISSUE TITLE
Scale writers when write is partitioned

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#10791]
Support writer scaling when write is partitioned, including partitioned or bucketed Hive or Iceberg tables, or OPTIMIZE (which may force repartitioning, overriding, preferred partitioning tuning knobs).

cc @sopel39

**Comment by vincentpoon** [comment]
+1 to this idea

**Comment by sopel39** [comment]
Relevant thread: https://trinodb.slack.com/archives/CFLB9AMBN/p1642961339264200

**Comment by sopel39** [comment]
This might be implemented by introducing a special `adaptive partitioned exchange`. Normally, row is assigned to a single partition based on hash. However, when there is a skew, a lot of rows will be assigned to the same partition. This will cause that specific partition buffer to be full.
The idea with `adaptive partitioned exchange` is that such exchange would keep track of `hash -> partition` assignments. When `adaptive partitioned exchange` gets a signal that particular partition buffer gets blocked, it would rebalance `hash -> partition` assignments. For example, it might decide that particular hash which is skewed would be distributed between two (deterministic) partitions in a round robin fashion.

**Comment by damnMeddlingKid** [comment]
Ran into this recently and thought it would be helpful to add some context on our case. We write to iceberg using transforms in our partition column (hour(), day() etc.). 

when using transforms in partition columns trino uses iceberg's bucket function for partitioning, this means that the planner can not choose writer scaling or redistributed writes. 

This leads to writer skew when we write a single large partition. 

## Steps
Heres a break down of what is happening:

1. IcebergMetadata sees that the partition spec contains transform columns so it creates a partition handle https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L700
2. LogicalPlanner sees that the connector has specified a partitionhandle so it creates a partitioningScheme based on this https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java#L591-L595
3. ApplyPreferredTableWriterPartitioning does not match this node because theres no preferred partitioning.
4. AddExchanges creates an exchange node based on the iceberg bucket function https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java#L634-L642

Heres a diagram that maps out all codepaths related to partitioned writes in iceberg.

<p align="center">
<img src="https://user-images.githubusercontent.com/422763/175412658-204a6c05-007f-4fff-8548-6b13d813b69e.png" width=300>
</p>

**Comment by damnMeddlingKid** [comment]
I'd like to work on this issue and I'm curious about the adaptive exchange idea and how it differs from the current implementation of writer scaling. I've tried a change which forces writer scaling and it works pretty well for iceberg, however we sometimes run into OOMs for hive based writes.

**Comment by sopel39** [comment]
This is fixed by writer scaling by @gaurav8297  (apart from optimize which is not scaled because we don't want to fragment files)
