### ISSUE TITLE
Avoid using duplicated link names in documentation

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11381]
Currently, we have two "General configuration properties" in JDBC connectors' documentation. The first is for `case-insensitive-name-matching`... and another is `unsupported-type-handling`... 

This generates links:
* https://trino.io/docs/current/connector/redshift.html#general-configuration-properties
* https://trino.io/docs/current/connector/redshift.html#id1

We should avoid this `#id(n)` style link because the name is unintuitive and the combination between link and body might be changed once we replace the order.

**Comment by dchvn** [comment]
Quick question: @ebyhr, because we are having two "General configuration properties" in /sphinx/connector/redshift.rst. So after generating by Sphinx, "General configuration properties" will have two conflict ids. Should we change the name of the configuration in  "Type mapping" from "General configuration properties" to "General configuration properties for type mapping"?
Many thanks!

**Comment by ebyhr** [comment]
@dchvn "General configuration properties for type mapping" looks too long. How about just "Type mapping configuration properties"?

**Comment by dchvn** [comment]
Sound good, raise a PR soon, thanks!

**Comment by dchvn** [comment]
Thanks 😄
