### ISSUE TITLE
Data loss due to lack of commit orchestration in Iceberg with Glue

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#11713]
Same as https://github.com/trinodb/trino/issues/9583 but for Iceberg with Glue

**Comment by findepi** [comment]
cc @alexjo2144 @homar

**Comment by rdblue** [comment]
@findepi can you share a few more details? I see the other issue was fixed by locking around an entire operation, but that should be unnecessary as long as you're configuring the right validations in Iceberg. What was the use case that caused this?

**Comment by findepi** [comment]
We shouldn't lock for the the entire write.
Still, we want to know the final update doesn't override some other thread's or cluster's update.
IIRC @jackye1995 was saying we should use Glue versioning API to implement compare-and-set semantics.

**Comment by alexjo2144** [comment]
> can you share a few more details?

@rdblue the commit orchestration for Glue leaves a little bit of time for a conflict to be committed where it won't cause a failure. The steps right now are:

1 Cache version number, i
2 Create new metadata file, i + 1
3 Fetch the table from Glue for the most recent metadata
4 Check most recent version == i
4a if true -> Update Glue table setting version to i + 1
4b Otherwise -> retry

Another writer can update the table between steps 3 and 4, resulting in two updates from i -> i + 1

**Comment by alexjo2144** [comment]
I missed this commit from @rajarshisarkar, looks like setting the versionId field to the version of the table the update is based on should do it https://github.com/apache/iceberg/pull/4166
