### ISSUE TITLE
Remove join spilling

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#11934]
Join spilling is very complex code and handling it does add a lot of complexity which makes it harder to move forward with join perf changes. Join spilling is not that essential anymore because of Tardiglade effort

**Comment by sopel39** [comment]
cc @trinodb/maintainers

**Comment by dain** [comment]
Our plan is to remove spilling entirely... it is just way to complex (and has always been).  You could switch to the Tardiglade instead

**Comment by pettyjamesm** [comment]
While tardigrade might be able to achieve some of the same benefits, my understanding of how it achieves them very different. I’d have to read up on the details a bit more, but at first glance I can’t see how we could leverage it in the same way we do spilling to disk today, in the context of Athena.

Right now, we’re able to run queries with very limited up front information about query characteristics. We execute in memory without spilling when possible and data can be spilled (securely) to local disk if the query requires it, without restarting the query and without requiring customers or automated systems to specify that at query submission time or execution start. We also don’t need to configure, scale, or manage external storage resources to do so, which for us in particular would be non trivial to accomplish in a way that required no customer configuration and cost overhead and was as secure.

If there’s a way to get the same benefits by using tardigrade without making significant compromises, then please let me know how that would work. Otherwise it would be removing a capability that we (and maybe others) depend on without replacement.

**Comment by dain** [comment]
I don't see anyway we keep the spilling code given the complexity it brings to the entire code base.  If you really want to see this maintained in Trino, then I suggest putting effort into redesigning this feature, so that it is isolated and has minimal impact on the overall codebase.... this feature is way over it's complexity budget.

**Comment by pettyjamesm** [comment]
Sure, let’s try to organize what specifically The problems this complexity creates and what changes are impossible to make in the current state of the implementation- and then let’s see what specific simplifying / refactoring changes that need to be made look like.

**Comment by sopel39** [comment]
> Sure, let’s try to organize what specifically The problems this complexity creates and what changes are impossible to make in the current state of the implementation- and then let’s see what specific simplifying / refactoring changes that need to be made look like.

@pettyjamesm from the top of the head:
* we would like to avoid `PartitionedLookupSource` as it's creates a performance bottleneck and it mitigates perf improvements from making join batch oriented
* we would like to construct lookup source on the fly. Currently, we wait for build side to be collected before we even start building build lookup source. This harms CPU utilization and query wall time

**Comment by pettyjamesm** [comment]
@sopel39 and I will sync up offline next week and see what we can come up with to refactor spilling in joins.

**Comment by sopel39** [comment]
Partially done as part of https://github.com/trinodb/trino/pull/12618. I think we can close for now
