### ISSUE TITLE
Some of the wiki's content is outdated

### ISSUE THREAD

**Issue by polaris6** [trinodb/trino#12366]
I found several issues in the wiki.

## The first issue:
![企业微信截图_9a589d60-e228-47d1-9195-54b3f3caf22b](https://user-images.githubusercontent.com/29967142/168196420-a821c657-5bab-4fcc-806f-80ec17e85ac1.png)

## The second issue:
![企业微信截图_d37ff3fd-0008-4130-8316-8a80c3a1f5bf](https://user-images.githubusercontent.com/29967142/168196463-abe2b3d3-3343-48db-84cb-0fcbcc4487f5.png)

## The third issue:
This document contains a lot of `Presto`, now it should be called `Trino`. I am willing to modify it if possible, but I seem to be able to modify it directly, without the review process.
![企业微信截图_67a68858-64ba-4048-9750-a652537ea389](https://user-images.githubusercontent.com/29967142/168196807-921db20f-e9d1-44b3-9eb0-3483f8fabbc1.png)

**Comment by polaris6** [comment]
cc @ebyhr @martint @dain

**Comment by hashhar** [comment]
Thanks for noticing @polaris6.

The changes you list all seem good to do and you can just edit the wiki to do so (thanks for letting us know the changes however). I don't know about the 2nd point though - will need Martin to answer that.

BTW the Security Troubleshooting Guide is using trino-admin which is no longer supported and doesn't work so will need to be rewritten either way. And that also seems like something that should be moved to the docs instead of the wiki. cc: @mosabua

**Comment by polaris6** [comment]
@hashhar Thanks for your reply.

I see that there are a lot of `Presto` in the code, I want to change them to `Trino`. I don't know if it is possible to change them at present, if it's possible, I'm willing to do it now.

I see that there is already a related issue also talking about this.
https://github.com/trinodb/trino/issues/10840

**Comment by mosabua** [comment]
Honestly I think nearly all of the content is historic only. Ideally it should get removed and migrated to the docs and the website as applicable.

**Comment by polaris6** [comment]
@mosabua Thanks for your reply,  since nearly all of the content is historical only and should be removed or migrated, I will not modify the content of this wiki.
