### ISSUE TITLE
Add support for rest api on connectors

### ISSUE THREAD

**Issue by avibhstarburst** [trinodb/trino#13905]
### Problem:
some connectors are using rest-api for internal configuration/management either internally (connector-workers) or externally for the user.
this requires the connector to start an internal server with a specific port.
major issues with this approach - 
1. adds to deployment requirements - requires another open port 
2. overloads trino server with another server(another jetty server with its memory, threads, cpu)
3. connector's rest-api is not handled by trino security 

### Solution Proposal:
expose a new interface "ConnectorRestApiHandler" through the "Connector".
the interface will have the same method signature as "javax.servlet.http.HttpServlet.service(...)" method. this will allow the connector to use the "io.airlift.jaxrs.JaxrsModule" module which handles the rest-api by creating a ServletContainer to handle it (using "io.airlift.jaxrs.JaxrsModule" is a valid option, but connector can use any other mechanism for its rest-api).

code interface as follows 
```
public interface ConnectorRestApiHandler
{
    void service(final HttpServletRequest req, final HttpServletResponse res);
}
```

the "ConnectorRestApiHandler" interface will be exposed through "ConnectorServices" and "CatalogServiceProviderModule" (same as the rest of the Connector's internals).

trino will have a new rest-api resource "RestCatalogProxyResource" which will consume the rest call and pass it to the connector's "ConnectorRestApiHandler".

here's an example of the get api 

```
    @ResourceSecurity(AUTHENTICATED_USER)
    @GET
    public Response proxyGet(
            @HeaderParam("X-Trino-Catalog") String catalogName,
            @Context HttpServletRequest servletRequest,
            @Context HttpServletResponse servletResponse)
    {
        return proxyJsonResponse(catalogName, servletRequest, servletResponse);
    }

    private Response proxyJsonResponse(String catalogName,
            HttpServletRequest servletRequest,
            HttpServletResponse servletResponse)
    {
        Catalog catalog = catalogManager.getCatalog(catalogName)
                .orElseThrow(() -> new IllegalArgumentException("No catalog registered for : " + catalogName));

        catalogServiceProvider.getService(catalog.getCatalogHandle())
                .orElseThrow(() -> new IllegalArgumentException("No rest-api registered for : " + catalogName))
                .service(servletRequest, servletResponse);
       
        // code which consumes the servletResponse and returns 'Response'
      ...
    }
```

example for connector's "catalog1" rest-api 
**GET http://localhost/v1/conf**

notes:
1. we're using "X-Trino-Catalog" header since the connector will get the full path as it was submitted to the proxy rest api. since catalog name is a variable we prefer not to add complexity for the connector's rest-api 
2. endpoint security is defined only on "RestCatalogProxyResource" and not on the catalog resources
3. rate-limiting is for all catalogs (which can also be an advantage)

**Comment by dain** [comment]
We talked about this a few years back.  There are a lot of difficulties with this design as wiht the isolated SPI classloader would not  be practicable to support a API like Java Servlet over the interface. It is imply to broad of an interface with too many connected classes.  Additionally, connectors may be using the Servlet APis internally and since this API is regularly updated there would be a large support burden.  This is why when we talked about this the interface was simply a way to pass a `String` between workers, and then the connector would encode a JSON document to do whatever you want.

Now days, I don't think this is possible at all.  We are moving to a design where we will support dynamically adding and removing catalogs at runtime and that means there can be multiple versions of the catalog running at the same time.  Additionally, catalogs do not necessarily need to be on all machines and the coordinator chooses where it wants to send tasks for catalogs.  This all means,  that there is no simple "send a message to this catalog on all workers", because the catalog only "exists" in the scope of a query transaction.  The system may (and likely will) decide to "cache" a catalog instance across transactions, but it does not have to.  The means that background tasks and communication are going to be faulty.  Instead, I expect you will need to run a separate server for this kind of background processing, or you will need to disable the dynamic catalogs feature which we expect to be popular.

**Comment by avibhstarburst** [comment]
@dain 
1. you're right, my pseudocode doesnt show how to run it in the connector classloader but it surely needs to be run there.
2. I'm not familiar with the dynamic catalog feature but I dont think this should be part of the engine. IMHO that should be part of the connector logic(knowing which version-worker to work with - not sure if this is available for the connector through the nodeManager). same as in any other app service out there who needs to deal with api versioning.
running a separate server inside the connector is actually the same, passing responsibility to the connector.
