### ISSUE TITLE
Allow for engine to scale writers per partition (bucket)

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#14042]
Currently, when `ConnectorPartitioningHandle` is provided by connector for insert, then each partition must be written by a single writer. However, some connectors support multiple files per bucket. Hence, bucket writes could be more efficient due to writer scaling.

This could be achieved by enabling connector to communicate to engine that partition doesn't have to be written by a single writer, e.g:
```
ConnectorPartitioningHandle#isSingleWriterPerPartition
```
or something similar.

cc @trinodb/maintainers

**Comment by ebyhr** [comment]
I guess this #13960 reporter faced this issue.

**Comment by findepi** [comment]
> However, some connectors support multiple files per bucket

Almost all connectors support this.
I think Hive ACID is probably the only exception.

> communicate to engine that partition doesn't have to be written by a single writer

i believe this is almost always true today

However, the reason why we don't distribute writes when `ConnectorPartitioningHandle` is present is because we have no way to estimate number of partitions. With identity partitioning (like in Hive or some cases in Iceberg), you can calculate number of partitions based on insert's source's stats. With bucketing, or any other kind of opaque function, we cannot calculate expected number of partitions to create.

This, however, doesn't limit us in context of writer scaling. Writer scaling is adaptive, we don't need the stats upfront, and opaqueness of the transform is hopefully not a problem, right?

**Comment by sopel39** [comment]
> However, the reason why we don't distribute writes when ConnectorPartitioningHandle is present is because we have no way to estimate number of partitions.

The idea is to extend partitioned writer scaling to buckets too. Then stats are not much relevant and user experience is better as insert is more resilient. cc @gaurav8297 

> This, however, doesn't limit us in context of writer scaling. Writer scaling is adaptive, we don't need the stats upfront, and opaqueness of the transform is hopefully not a problem, right?

Exactly.

**Comment by sopel39** [comment]
this is completed
