### ISSUE TITLE
ERROR main io.trino.server.Server Configuration is invalid

### ISSUE THREAD

**Issue by kvishe** [trinodb/trino#14136]
We are upgrading the server to newer version 380 with our old configuration but getting below error.

ERROR main io.trino.server.Server Configuration is invalid

Errors:
1) Defunct property 'experimental.spill-order-by' (class [class 10.trino.FeaturesConfig]) cannot be configured.
2) Defunct property 'experimental.spill-window-operator' (class [class io.trino. FeaturesConfig]) cannot be configured.
3) Defunct property 'experimental.reserved-pool-enabled' (class [class io.trino.memory.NodeMemoryConfig]) cannot be configured.
4) Configuration property 'experimental.reserved-pool-enabled' was not used 
5) Configuration property 'experimental.spill-order-by' was not used
6) Configuration property 'experimental.spill-window-operator' was not used

What are replacements for these configuration property?

**Comment by hashhar** [comment]
The fine grained spill toggles are not needed anymore - they were added as a kill switch.
You can remove all of them and replace with just `spill-enabled`.

Re: reserved pool - reserved pool was removed in 372 since it led to underutilization of clusters. You can remove that as well.

Note that all of this is documented in the release notes for the versions in which these changes were introduced.
