### ISSUE TITLE
Metadata queries in fault-tolerant execution is slow due to going through exchange spooling

### ISSUE THREAD

**Issue by linzebing** [trinodb/trino#14767]
Queries like "show catalogs", "show tables" will write result to spooling storage first before returning to the client. This is not very reasonable, and ideally result should be streamed back in this case.

**Comment by findepi** [comment]
> Queries like "show catalogs", "show tables"

I wouldn't call them "DML queries"
let's call it "Metadata queries" maybe

**Comment by losipiuk** [comment]
@linzebing @findepi 

Is this really a pain point? I am leaning towards closing this one unless we see a big issue with that. 
There was a problem when such queries were queued on resource allocation due to requesting significant memory.
But it was already fixed via https://github.com/trinodb/trino/pull/19027.

**Comment by findepi** [comment]
perhaps this is solved. 🤷‍♂️ .

especially if we don't have any latency issues for these queries

**Comment by losipiuk** [comment]
Closing as wont-do
