### ISSUE TITLE
Add "Peak total memory" to event-listener's QueryStatistics

### ISSUE THREAD

**Issue by gafeol** [trinodb/trino#15112]
I'm running a few query benchmarks and I use the event listener to report query metrics, but I couldn't find a way to report a query's "Peak total memory" as shown in the UI through a QueryCompletedEvent. 
Would it be possible to add this metric to the QueryStatistics class so we could report it?

![image](https://user-images.githubusercontent.com/12179028/202819015-a546f0ba-671a-49d5-87a3-565bc5b91a1b.png)

**Comment by weijiii** [comment]
@gafeol 
IIUC the value from UI can be obtained programmatically with this [method](https://github.com/trinodb/trino/blob/0c699e86243e033e8c353688f821b3258e2e5635/core/trino-main/src/main/java/io/trino/server/BasicQueryStats.java#L315). 
This value is not included when the QueryCompletedEvent is constructed, but you can probably modify QueryStatistics and QueryMonitor so that it is exposed in the event objects.

**Comment by raunaqmorarka** [comment]
peakUserMemoryBytes in QueryStatistics should give you almost the same thing.
