### ISSUE TITLE
Version 394 LIKE expression slowness issue

### ISSUE THREAD

**Issue by Theo-Lo** [trinodb/trino#15778]
Hi, I met a query slowness issue after version upgrade. We originally were using version 390 but later when we upgraded to version 400, our query has been running much slower. We find that in our query, there is a part where we have some LIKE expression together with wildcard "%" usage as below:
LEFT JOIN testing_schema.testing_table ON
    UPPER(DT.log) **LIKE** UPPER(CONCAT('**%** ', testing_schema.testing_table.loglevel,' **%**'))
    OR UPPER(DT.log) **LIKE** UPPER(CONCAT('**%**[', testing_schema.testing_table.loglevel,']**%**'))
    OR UPPER(DT.log) **LIKE** UPPER(CONCAT('**%**[', testing_schema.testing_table.loglevel,'ing]**%**'))
    OR UPPER(DT.log) **LIKE** UPPER(CONCAT('**%**<', testing_schema.testing_table.loglevel,'>**%**'))
We have gone through some testing, and by removing the "%" in the LIKE expression, it will be much faster.

We have been testing through different version and find that since version 394, this slowness issue occurs to our query when we have LIKE expression while using "%".
For the same query in version 393, it only takes 41s to get the result. But in version 394, it takes 13m35s, and all the version behind are also taking similar time.

I find that in version 394 release note, there is an update for LIKE expression as below:
Improve performance of LIKE expressions. ([#13479](https://github.com/trinodb/trino/issues/13479))

I have read this commit, but this commit should aim to help improve our performance instead of slowing it down. So, I do wonder if you have any insight about this issue, since this commit happen to match with our finding for the slowness using LIKE expression with "%" since version 394.

Thank you.

**Comment by raunaqmorarka** [comment]
cc: @martint @gaurav8297

**Comment by davseitsev** [comment]
We faced the same issue after Trino upgrade from 367 to 407.
Query simplified example:

```
select * from sandbox.test.views v
inner join sandbox.test.urls u
  on v.url like concat(concat('%',u.url),'123%')
```

On Trino 367 the query processes 178M rows and consumes about 12h CPU.
On Trino 407 the query processes 800K rows and fails due to exceeding `query.max-cpu-time=48.00h`

My investigation showed that [LikeMatcher.compile](https://github.com/trinodb/trino/blob/6238bdc63065c486e1edeb7e73c552bb3a652773/core/trino-main/src/main/java/io/trino/type/LikeFunctions.java#L62) takes 75% of CPU time. And it lead me to this issue.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/1793410/220380054-de7f5e5f-241b-4553-8fcd-54898b3a7b1d.png">

As far as I understand it's a corner case when Trino have to compile `like` pattern for each row.

**Comment by martint** [comment]
This is fixed by https://github.com/trinodb/trino/pull/15999
