### ISSUE TITLE
Allow test QueryRunners to customize extra properties

### ISSUE THREAD

**Issue by kaklakariada** [trinodb/trino#16011]
We are creating a connector for the [Exasol database](https://www.exasol.com/). Exasol requires [additional configuration](https://exasol.my.site.com/s/article/Parallel-connections-with-JDBC?language=en_US) to support parallel inserts, which I want to avoid for the initial version. That's why I would like to set extra property `task.writer-count` to `1` when creating the query runner in with the following statement:

```java
            queryRunner = DistributedQueryRunner.builder(createSession())
                    .setExtraProperties(extraProperties)
                    .build();
```

But `TestingTrinoServer` sets this property to `2`, causing a duplicate key error when creating the Map. Would it be possible for you to modify this, so that connectors can overwrite properties when creating the `DistributedQueryRunner`?

**Comment by Praveen2112** [comment]
Thanks a lot for your initiative on contributing a new connector to Trino. 

Instead of restricting `task.writer-count` to 1 - Can we have an initial read-only version and then we could add support for writes with parallel inserts ?

Ideally the connector shouldn't depend on any of the query engine configuration properties and   
`task.writer-count > 1`, as this allows to expose writer-concurrency related bugs. 

Plus `task.writer-count` is one way of controlling the number of writers - in case of queries which involve shuffling of data - like aggregation and join there will be a tasks for each bucket of data and we might not be able control the number of task created. 

We do have some JDBC based connector like Druid which doesn't support writes yet, we can have a similar strategy for `Exasol` and we could implement write support as a follow-up.

Looking forward for your new PR.

**Comment by Praveen2112** [comment]
I'll be closing this issue. If you face any hurdles on implementing the new connector - we can follow-up the discussion [here](https://github.com/trinodb/trino/issues/16083). Feel free to join our [slack community](https://join.slack.com/t/trinodb/shared_invite/zt-1p7epe8c3-Tr~oeOEyXvSXRd5UWag4LA) and we could continue the discussion there.

**Comment by kaklakariada** [comment]
@Praveen2112 thank you for your reply and for the note about Druid. I will check how it is implemented there.
