### ISSUE TITLE
'NOT_SUPPORTED: Unsupported Trino column type (date) for Parquet column ([today] optional int64 today (TIMESTAMP(MICROS,false)))

### ISSUE THREAD

**Issue by BAlvernaz** [trinodb/trino#17733]
I just recently started to get this error when trying to load Data Stored in my AWS DataCatalog. 

Background Process showing the error.
'NOT_SUPPORTED: Unsupported Trino column type (date) for Parquet column ([today] optional int64 today (TIMESTAMP(MICROS,false)))'

Its using pyathena to query the Data Catalog.

**Comment by raunaqmorarka** [comment]
You're attempting to read parquet data that is annotated as timestamp as date type in Trino. This happened to work in the old parquet reader because it didn't check for mismatch between parquet and trino data types until it encountered non-null data. The new parquet reader does this check more eagerly. Related issue https://github.com/trinodb/trino/issues/12073
You can get past this by updating the data type in the table definition to timestamp.

**Comment by akenO8** [comment]
When I used spark to migrate the hive table to the iceberg table, the trino query reported an error:
`Unsupported Trino column type (timestamp(6) with time zone) for Parquet column ([stime] optional int96 stime = 1)`

**Comment by raunaqmorarka** [comment]
> When I used spark to migrate the hive table to the iceberg table, the trino query reported an error:
> `Unsupported Trino column type (timestamp(6) with time zone) for Parquet column ([stime] optional int96 stime = 1)`

That's a different problem, please file a separate issue for it. Currently we support reading INT96 as `timestamp with time zone` only for precision 0 or 3. Micros precision is supported only when timestamps are stored as INT64 in parquet.

**Comment by eswarichandana** [comment]
Just a doubt, if I change the data type from date to timestamp for the column will it create any data related issues here.
