### ISSUE TITLE
Add support for `OCTETS` char length unit option in `SUBSTRING`

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#17868]
```sql
<character substring function> ::=
  SUBSTRING <left paren>  <character value expression>  FROM <start position> 
      [ FOR <string length>  ] [ USING <char length units>  ] <right paren> 

<char length units> ::=
    CHARACTERS
  | OCTETS
```

Relates to https://github.com/trinodb/trino/discussions/17719

**Comment by martint** [comment]
Supporting OCTETS doesn’t seem very useful for UTF-8 strings. It’s not clear what the result should be if the boundary falls in the middle of a UTF-8 character. 

The spec says the result is implementation dependent, but the only behavior that seems reasonable to me is to produce an error. Since it’s hard for the user to predict whether that will happen for an arbitrary string, I can’t think of a use case where one would want to use it in a query.
