### ISSUE TITLE
Trino makes multiple S3 GetObject requests to a parquet file

### ISSUE THREAD

**Issue by sugichy** [trinodb/trino#18411]
Trino makes two GetObject requests when querying a parquet file in S3.
My test conditions:
- Configured hive.properties to use Glue catalog
- Executed a query "select * from glue_table_name" from trino-cli
- Glue table has s3 path that include a parquet file

In my test, Trino made two GetObject requerst for the same file with different bytesTransferredOut:
- 1 GetObject for bytesTransferredOut=911
- 1 GetObject for bytesTransferredOut=345
These are the size of the entire parquet file (911 byte) and the result (345 byte) of `parquet-tools size`.
```
$ parquet-tools size -d part-00000-filename.snappy.parquet 
part-00000-filename.snappy.parquet: 345 bytes
Total Size: 345 bytes
```

Thus, I guess Trino is executing additional GetObject API to get parquet metadata.
Compared to Presto, GetObjectMetadataRequest is added in Trino. This might be related to this behavior.

https://github.com/trinodb/trino/blob/adef5f4754eb0edbeed23790d8520ead38ae0ad9/lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/TrinoS3FileSystem.java
https://github.com/prestodb/presto/blob/420af675d1a372520eaf871664b0d9535dc62f4e/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java

Does anyone know if it is a necessary and intended change?
If not, can we remove unnecessary S3 API request?

**Comment by raunaqmorarka** [comment]
The first GET request is for reading file footer, subsequent GET requests for fetching the data are made after reading metadata from file footer. It only looks like an extra request because you're working with a tiny file that is smaller than typical file footer size. The 1st file footer read GETs a few kBs from the end of file because size of the footer is not known upfront. On typical files (greater than a few MBs), you should see a small read for file footer followed by larger reads for the columns.
