### ISSUE TITLE
IpAddressFunctions.contains should return False instead of raising an exception on IP version mismatch

### ISSUE THREAD

**Issue by mvanderlee** [trinodb/trino#18497]
I have an IP field that contains a mix of IPv4 and IPv6 addresses. I want to get all rows where the IP is in a CIDR. But I get the following exception: 
```
TrinoUserError(type=USER_ERROR, name=INVALID_FUNCTION_ARGUMENT, message="IP address version should be the same", query_id=...)
```

The expected behaviour would be to return False as the IP is not in the CIDR

**Comment by Sartan4455** [comment]
I get this too.  Our field is initiator_ip and responder_ip.  How do I use this if I have a mix of ipv4 and ipv6?

**Comment by Sartan4455** [comment]
I had to do a stupid fix:
 cast(cast(sessions.initiator_ip as IPADDRESS) as VARCHAR) NOT LIKE '%:%'

**Comment by hashhar** [comment]
@martint

**Comment by hashhar** [comment]
There's a lot of useful context and discussion in https://trinodb.slack.com/archives/CGB0QHWSW/p1693949616277459 so linking it here as well.

**Comment by martint** [comment]
This would be a good improvement to make. We tried to be conservative in the initial implementation (https://github.com/trinodb/trino/pull/110) because we didn't have a good understanding of how this should work in the context of mixed IPv4/6 addresses and CIDRs. It's always easy to relax and expand behaviors that are currently not supported, but the opposite can be problematic.

**Comment by Sartan4455** [comment]
One of the issues I have is that I don't have a static string I have a whole column of ip addresses in varbinary format that could be either v4 or v6.  I am thinking the issue could be related to casting  to IPADDRESS where the cast forces ipv4 or ipv6
For instance take the data from a table 'sessions'
The first is an ipv4 and the second is an ipv6
```
                 initiator_ip                   
------------------------------------------------
00 00 00 00 00 00 00 00 00 00 ff ff 0a 01 03 b9 
fe 80 00 00 00 00 00 00 05 ae ea 5e 70 9c bd 32
```
Instead of a known string that is ipv4 or 6
`SELECT contains('10.0.0.0/8', ~~IPADDRESS '10.255.255.255'~~) from sessions;`  <--- known only ipv4
`SELECT contains('10.0.0.0/8', cast(initiator_ip as IPADDRESS)) from sessions;`
The cast may be what is causing the issue, it can't be controlled to return the matching address version.
The ineloquent solution I have is to include  a where condition that makes sure the results are only the correct versions.  I came up with
`where regexp_like(cast(cast(sessions.initiator_ip as IPADDRESS) as VARCHAR),':')`
and I had a smart colleague come up with
`where substr(initiator_ip, 1, 12) != lpad(from_hex('FFFF'), 12, from_hex('00'));`

**Comment by mvanderlee** [comment]
Our usecase: string column of IP4 and IP6 values. 
Our queries are being build by our own builder tool, so we just check if the CIDR value contains a dot or colon and add a LIKE filter to the query. 
`"ip_field LIKE '%.%' AND contains('10.0.0.0/8', CAST("ip_field" as IPADDRESS))`

Python code using the pika library:
```python
def IpInCidr(term: Term, cidr, alias: str = None):
    # Need to ensure we compare IPv4 to IPv4 CIDR and IPv6 to IPv6 CIDR
    # https://github.com/trinodb/trino/issues/18497
    char = '.' if '.' in cidr else ':'

    return term.like(f'%{char}%') & Contains(cidr, Cast(term, 'IPADDRESS'), alias=alias)
```

**Comment by Sartan4455** [comment]
@mvanderlee  Does that actually work for you?  

I have large amounts of data, and it seems that the planner decides to split the query and work on the contains and the 'like' or other filter clause. So it'll get some results but then eventually one of the splits will throw an exception.  

So queries like this
```
select 
   initiator_ip 
from 
   subsessions 
where 
    substr(initiator_ip, 1, 12) = from_hex('00000000000000000000FFFF')
AND
    contains('172.16.0.0/12', CAST(subsessions.initiator_ip AS IPADDRESS))
```
or

```
select
    cast(initiator_ip as IPADDRESS)
from
    sessions
where
    cast(cast(sessions.initiator_ip as IPADDRESS) as VARCHAR) like '%.%'
and 
   contains('10.0.0.0/8', cast(initiator_ip AS IPADDRESS));
```

can still fail if the planner splits in certain ways.

SQL is about describing what you want and letting the planner do it - but the only way I can think to force a do the first part first before the second part is with a subselect or CTE.


@martint Sadly I am not proficient in java to do any kind of decent fix myself.    Is there any chance a fix for this could be prioritized?   We have many clients that use cidr filters. 
It does seems like in IpAddressFunctions.java that his line could return false instead.
 if (base.length != ipAddress.length) {
        ~~throw new TrinoException(INVALID_FUNCTION_ARGUMENT, "IP address version should be the same");~~
            return false;
 }

**Comment by Sartan4455** [comment]
also seems like a test case of something like
   assertFunction("contains('127.0.0.1/32', IPADDRESS '64:ff9a:f:f:f:f:f:f')", BOOLEAN, false);

**Comment by Sartan4455** [comment]
I added a pull request (https://github.com/trinodb/trino/pull/18962) but need to get the CLA signed.

**Comment by martint** [comment]
This is actually more complicated, and it brings us back to why we didn't implement when we added this function:

* According to [RFC 4291](https://datatracker.ietf.org/doc/html/rfc4291.html, there are two ways IPv4 addresses can be embedded in an IPv6 address:
** compat mode: the IPv4 address is encoded in the lower bits. Therefore an address such as `170.187.204.221` (0xAA, 0xBB, 0xCC, 0xDD) would turn into `::AABB:CCDD`
** mapped mode: the IPv4 address is encoded in the lower bits, but it's preceded by a `0xFFFF` segment. The address above would be encoded as `::FFFF:AABB:CCDD`
* According to the 6to4 scheme in [RFC 3056](https://datatracker.ietf.org/doc/html/rfc3056#section-2), IPv4 addresses are embedded in IPv6 space using a prefix of `2002::/16`. The address above would be encoded as `2002:AABB:CCDD:xxxx...`

Given this, it's not clear to me how an IPv6 CIDR should or shouldn't match an IPv4 address, and viceversa. For instance:
* Does `0:0:0:0:0:FFFF::/96` contain `170.187.204.221`? 
* Does `170.187.204.221/32` contain `0:0:0:0:0:FFFF:AABB:CCDD`?
* Does `0:0:0:0:0:0::/96` contain `170.187.204.221`? 
* Does `170.187.204.221/32` contain `0:0:0:0:0:0000:AABB:CCDD`?
* Does `2002::/16` contain `170.187.204.221`?
* Does `170.187.204.221/32` contain `2002:AABB:CCDD:0:0:0:0:0`?

**Comment by martint** [comment]
compat mode seems to be deprecated, and the 6to4 scheme appears to be a mechanism for routing between IPv6 networks via the IPv4 network, so it doesn't seem relevant. So that leaves us with mapped mode, which means that from the list above, only these should be true:

* Does `0:0:0:0:0:FFFF::/96` contain `170.187.204.221`?
* Does `170.187.204.221/32` contain `0:0:0:0:0:FFFF:AABB:CCDD`?

**Comment by martint** [comment]
@Sartan4455, here's a more comprehensive implementation for this: https://github.com/trinodb/trino/pull/18997

**Comment by Sartan4455** [comment]
That is definitely more in depth and better then what I understand. And I am the first to admit that my understanding is not great.  I just knew the exception was a big impasse.  
That's amazing.

**Comment by mvanderlee** [comment]
Fantastic, Thanks for the quick and comprehensive fix @martint

**Comment by Sartan4455** [comment]
We rolled out 427 - fix so far works great.  Speeds up queries and reduces query complexity!  Tremendous thanks to @martint
