### ISSUE TITLE
Create RPM for Trino CLI

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#1882]
Currently users need to go to Maven Central to download Presto CLI Jar (and make it executable).

**Comment by hashhar** [comment]
@sopel39 Should this be done in a similar manner as it is done for presto-server by introducing a new maven module? Or should I add an execution within the presto-cli module to create the rpm as an artifact?

**Comment by sopel39** [comment]
I think it should be the simplest way possible. IMO we could keep it in `presto-cli` module (@electrum ?). We separated dedicated module for Presto server RPM so that we can exclude that module when not needed as it takes time to build. Build presto-cli RPM should be much quicker.

**Comment by hashhar** [comment]
I tried implementing this and it turns out Maven/Plugins doesn't provide an easy way/recommend to use the artifact of a module as input within the same module.

I'm now implementing it similar to how `presto-server-rpm` is implemented, `presto-cli-rpm` will use `provisio` to use the executable jar as an input artifact and then add that to an RPM using the existing RPM plugin used in `presto-server-rpm`.

Since the RPM plugin will now be used in two different modules should I move it to `<pluginManagement>` in the aggregator pom? Or at least the version number?

**Comment by sopel39** [comment]
> Since the RPM plugin will now be used in two different modules should I move it to <pluginManagement> in the aggregator pom?

I think it's a good idea

**Comment by findepi** [comment]
I don't think people ask for an RPM for the CLI very often. Actually, i personally don't recall being asked about this even once.
Maybe for the sake of simplicity we don't do that?

**Comment by hashhar** [comment]
I agree. I initially jumped on this because it was a "good first issue" and I was new to the code. I too haven't seen the need specially given the fact that the CLI is a standalone executable JAR without any dependencies.

**Comment by sopel39** [comment]
Closing for now as it has little demand
