### ISSUE TITLE
Behavior difference between OpenCSV native implementation and hive serde

### ISSUE THREAD

**Issue by guptashailesh92** [trinodb/trino#18918]
When I create a table with csv data, where quote character and escape character are same, it throws an error with the native csv implementation (`Quote and escape characters cannot be the same`) whereas with hive it provides the expected output..

```
eg
data.csv

"""""col1","col2"

 CREATE TABLE t1 (
    a varchar,
    b varchar   
 )
 WITH (
    csv_escape = '"',
    csv_quote = '"',
    external_location = 's3://<>',
    format = 'CSV'
 )

Output with hive serde 
trino:default> select * from t1;
   a    |  b
--------+------
 ""col1 | col2

Output with native implementation
Query 20230905_051701_00009_dhywj failed: Quote and escape character cannot be the same

If i disable the checkArgument, then it shows 
trino:default> select * from t1;
  a   |  b
------+------
 col1 | col2
(1 row)
```

q1. What was the thought behind adding the checkArgument? Is it a limitation with native implementation?
q2. Any hack to achieve the same behavior as hive serde?

**Comment by dain** [comment]
@guptashailesh92 The check is there because the underlying CSV parser in Hive, OpenCSV, performs this check. This is not the version that Hive uses, but you can see the check [here](https://github.com/quux00/opencsv/blob/master/src/au/com/bytecode/opencsv/CSVParser.java#L188C9-L190).  For example, if you set the quote and escape characters both to `*` you will get an error.

But your code above work, so why?  Well it is because of [this code in Hive](https://github.com/apache/hive/blob/master/serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java#L181-L185).  Basically, if the escape character is `"` (char 34) then it calls a different constructor for OpenCSV which changes the escape character to `\\`.  

As with all thing in Hive, this crazy behavior has crazy side-effects.  If you now create a table with escape character `\\` and quote character `"` in Hive, you get an error saying the quote and escape character are the same... insane stuff.

Anyway, this code is [supposed](https://github.com/trinodb/trino/blob/master/lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/csv/CsvDeserializer.java#L35) to be bug for bug compatible with Hive, so this needs to be fixed.

**Comment by dain** [comment]
Oh ya, I forgot about this.  If you set the escape character to `"`, the Hive code will serialize by escaping with `"`, but when you read, Hive will swap the escape character with `\\`, so you can not read the data you wrote.

**Comment by guptashailesh92** [comment]
thank you.
