### ISSUE TITLE
Run trino-filesystem tests on Azure from CI

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#18998]
Currently tests are disabled as required env variables are not set in ci.yml

**Comment by charlesjmorgan** [comment]
There are two TODOs to run the azure trino filesystem cloud tests:
1. Add secrets to CI for the 3 abfs account kinds: blob, gen2flat, gen2hierarchical
2. Optionally dynamically create storage accounts for each run of the azure cloud tests since it requires an empty account. 
This was already [added previously for S3](https://github.com/trinodb/trino/pull/19060)

Just doing number 1 is sufficient for now
