### ISSUE TITLE
openx.data.jsonserde.JsonSerDe does not respect "case.insensitive" = "TRUE" for map keys

### ISSUE THREAD

**Issue by ubyyj** [trinodb/trino#20400]
for map keys, Trino does not convert the key into lowercase when SERDEPROPERTIES contains "case.insensitive" = "TRUE", while native hive does.

for json file with content:
`{"ab":{"cD":0}}`

create the following hive table:
```
CREATE EXTERNAL TABLE `test` (
    `ab` map<string, integer> COMMENT 'from deserializer'
)
ROW FORMAT SERDE 
'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES ( 
    "case.insensitive" = "TRUE"
)
STORED AS INPUTFORMAT
'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT 
'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
 's3://...'
```

Hive returns key as 'cd', in lowercase, but in Trino (435) returns key as 'cD', does not respect the insensitive setting.

**Comment by dain** [comment]
The OpenX json format is in Trino is described [here](https://github.com/trinodb/trino/blob/master/lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/openxjson/README.md#openx-json-format).  The OpenX Json format has many forks because it was effectively abandonded many years ago, and these forks have diverged quite a bit.  The document describes the chosen implementation for Trino and how it differs.  The correctness of our implementation is measured against that document, so in this case the implementation is considered correct.  Please read the document for more details.

This specific difference is describe [here](https://github.com/trinodb/trino/blob/master/lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/openxjson/README.md#known-differences-9).
