### ISSUE TITLE
Add tolerance for catalogs which do not boostrap

### ISSUE THREAD

**Issue by ChrisSandison** [trinodb/trino#20466]
I recently ran into an issue with the Bigquery connector the client secrets being supplied could not properly be parsed into a JSON. While I can ensure that invalid credentials won't be loaded, it would be nice to have an option to have it disregard catalogs that do not bootstrap properly due to exceptions being thrown by the underlying plugin, since this causes the entirety of Trino's bootstrap process to fail

**Comment by hashhar** [comment]
how do you propose such errors be shown to cluster admins then?
The risk is that you can have missing catalogs and not notice or realise why.

People don't read warnings in the log anyway.

**Comment by dain** [comment]
If you run in the experimental dynamic catalogs mode, catalog setup exceptions do not prevent server startup.  The leaves the catalog in "broken" mode where it only throws an exception.  Then someone with the proper priviledge would need to "create or replace" the catalog (since we have not added alter catalog yet).

For the static catalog mode, I don't see us implementing this because it would result in a broken catalog until the config is fixe and the server restarted.
