### ISSUE TITLE
Special characters support in extra credentials.

### ISSUE THREAD

**Issue by ddl-joyce-zhao** [trinodb/trino#21751]
Query fails if there are following special characters in the extra credentials.

- ` = ` Message: trino: query failed (400 Bad Request): "Invalid X-Trino-Extra-Credential header"

- `%` Message: trino: query failed (400 Bad Request): "Invalid X-Trino-Extra-Credential header: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 1 in: \"do\""

- `+ ` Message: trino: query failed (200 OK): "io.trino.spi.TrinoException: [10]: authentication failed: Detailed info for this error can be found with correlation ID '6BDD97D810581241A472BA8974EEF6D9'"

- ` , ` Message: trino: query failed (400 Bad Request): "Invalid X-Trino-Extra-Credential header"

These special characters are commonly used in passwords and should be supported.

**Comment by hashhar** [comment]
URL encode the values. It's an HTTP header and not all values are supported. e.g. non-ASCII values will also have issues. See https://github.com/trinodb/trino/blob/d8929197dd4485c0a3cf149b6f858445faf4d6a4/client/trino-client/src/main/java/io/trino/client/StatementClientV1.java#L183-L186 for an example of how trino-client does this.

Closing since this already works provided you are passing the values correctly. Existing clients like JDBC, Python client etc. already do this properly.
