### ISSUE TITLE
Username is visible in Trino UI in plaintext form

### ISSUE THREAD

**Issue by hafizmujadidKhalid** [trinodb/trino#22394]
Dear Trino community,

At the moment, the User name (email) is visible in Trino UI in plaintext format. There is no option where we can encrypt/hash this field on Trino UI to be GDPR/data privacy compliant. We need to have some trinoo web UI property to hash/encrypt username.

**Comment by hashhar** [comment]
the detail is only resident in memory for the last `query.max-history` queries (default 100). 

So either restart cluster or run more than 100 queries for the information to disappear.

Also note that the proper way to "hide" information is to use system access control so that each user can only view their own queries on the UI (so no information leak).

I'm closing since I don't think this is a relevant request. (At the very least users MUST be able to see their own information, if you want to prevent cross-user information view then use the access control in Trino to configure that).
