### ISSUE TITLE
Allowing clients to send auth over http connections

### ISSUE THREAD

**Issue by benjie332** [trinodb/trino#23410]
### Background
We are running a small cluster of apps that are powered by Trino queries to a shared database, the output of which is visible and allows user interaction via Grafana dashboards. We would like to secure the cluster as a whole, by setting up secure ingresses to the cluster. We would like to keep the connections between the individual apps as simple as possible, using plain HTTP, to ensure that the cluster can be used in a wide variety of different environments and tools (eg. Istio).

### Current problem
All Trino clients have hardcoded checks to ensure that username/password authentication can only happen over HTTPS connections. This requires us to secure all the individual internal connections to Trino, greatly complicating the overall architecture and means of deployment.

### Proposal
Allowing authentication (username/password) to be used over HTTP connections, and dropping the hardcoded check for HTTPS/SSL in these clients:
- Java JDBC and HTTP
- Go client
- Grafana plugin 

This would mean rather than throwing exceptions/errors on detecting a username/password and no SSL configuration, the clients will allow the connection to be made.

### Rationale
Trino itself offers the ability to trust that connections come from TLS-terminated ingresses, then have the final hop of the connection be made over HTTP. Trino also has the option of allowing traffic between coordinators and workers to happen over HTTP.

Dropping the hard requirement in the clients allows this logic to be extended to entire clusters of apps, rather than just the immediate connection to Trino.

We would be happy to contribute in the implementation, if this proposal is considered useful.

cc @davinkevin

**Comment by mosabua** [comment]
Allowing such an insecure setup is not something we would merge in Trino. cc @dain

**Comment by dain** [comment]
We have have a hard requirement that Trino does not allow credentials to move over insecure connections from clients.  We simply do not want to get into the mess that other databases have with insecure credential transfer.  We do allow not TLS traffic from a reverse proxy and we also allow traffic between servers to be in plain text, as many organizations have network security guarantees that  make this secure enough.

In your case, if your traffic is completely private, I'd suggest you work inside your organization to setup a private CA.  Assuming you are in the cloud this should be pretty easy.

**Comment by davinkevin** [comment]
Hello @dain, 

I totally understand that, but in some context it can be detrimental to the cause. In our context, we run the system in k8s using tool like Istio for observability and security. 

The problem with this Trino requirement is that creates TLS inside mTLS, that is very inefficient… and this prevents the system to be observable because requests are encrypted on the wire by trino a second time, not readable by infrastructure for support and operation.

Additionally, in company with many workloads, they prefer to manage a unique way to configure security with `mTLS` rather than one-per-tool… because let's be honest, one-per-tool doesn't scale. If you have many workloads (10, 100, 1000…), it's impossible to configure each of them , without requiring a dedicated team for that (and not counting the time to do the PKI management and certificate rotation with downtime it creates). With tooling like istio, it's a 7 lines YAML and that is done. 

We are available to discuss with you potential solutions or alternatives to achieve that.
