### ISSUE TITLE
Restrict maximum amount of queries shown in UI when MySQL event listener is used

### ISSUE THREAD

**Issue by konovenski** [trinodb/trino#23886]
When MySQL event listener is used and queries are persistent, the UI selector allows you to pick between showing 20, 50, 100 and all queries. The "all" option is problematic in this case, since it will return full content of "select  * from trino_queries". There should be an option to disable that setting, or it should just be disabled by default when using the event listener

**Comment by Praveen2112** [comment]
How about configuring `query.max-history` and `query.min-expire-age` to restrict the `SELECT * FROM TRINO_QUERIES` won't it reduce the load in the UI side ?

**Comment by konovenski** [comment]
We will try that, thanks!

**Comment by konovenski** [comment]
@Praveen2112 default value of query.max-history is 100, and looks like it is not affecting the mysql database. We want to have a full query retention, but the console should not output all of them

**Comment by nikita-sheremet-java-developer** [comment]
@Praveen2112 
The first,
I think there should be different task/issue - "Make Trino UI show paginated queries output". Because for now UI can not show more than 2000 queries (on my machine)

The second,
`MySQL event listener ` - is not used on UI. UI works independed. It shows queries from coordintor HashMap, not MySql database. So the HashMap is limited with `query.max-history` and `query.min-expire-age`.

**Comment by hashhar** [comment]
MySQL event listener is not used to return queries to the UI so this issue is not actionable.

As Praveen already said if you feel the default "all" of 100 is too high you can lower it as needed.
