### ISSUE TITLE
Timestamp differs when queried from presto and trino with mysql databases.

### ISSUE THREAD

**Issue by naveenbussari** [trinodb/trino#23960]
We currently have presto running on kubernetes. 
We are exploring migrating from presto to trino(in the same kubernetes cluster)

We are facing issues with the timestamp specifically with the mysql database. 
Trino is returning the values in timestamp column in UTC where as the actual mysql db stores timestamp in (IST) Asia/Kolkata timezone.

trino version: 432

The actual **mysql** databases stores the timestamp in IST ( Asia/Kolkata )

![Image](https://github.com/user-attachments/assets/d3da0046-8869-422b-80e3-f46c1577be04)

When queried from **Presto** , the data is returned as it is in mysql db i.e., Asia/Kolkata timezone.

![Image](https://github.com/user-attachments/assets/5cd6d04a-c0a5-45c8-b259-d10a3e116ff9)

When queried from **Trino**, the data is returned in UTC timezone.

![Image](https://github.com/user-attachments/assets/4f946630-30de-49dd-8f3c-caf441b19d82)

I tried adding the property ```serverTimezone=Asia/Kolkata ``` . But this didn't work.

When I use the ```AT TIME ZONE``` clause with the query in trino it works,
![Image](https://github.com/user-attachments/assets/3db18320-374e-4522-8d3d-4f1ae7c79538)

This is happening **only with mySQL** databases but not postgreSQL. 
I have checked  with multiple catalogs and databases.
In postgres databases, the results are in IST in Presto as well as Trino as it is stored in the actual postgres database.

How can I get the values in timestamp column in Asia/Kolkata timezone?

**Comment by martint** [comment]
cc @hashhar @ebyhr

**Comment by naveenbussari** [comment]
@ebyhr 
could you please help here

**Comment by hashhar** [comment]
@naveenbussari Can you try on a version after Trino 427. We changed type mapping for exactly this reason - https://github.com/trinodb/trino/commit/fd5b247b7a20a03ad8b1157aed7eb22990ab0682

Alternatively please share more details to reproduce with at-least:

- table DDL from MySQL
- `SHOW CREATE TABLE` from Trino (so we can see how the types got mapped)

**Comment by hashhar** [comment]
Oh I see why you are confused. This seems to be working correctly.

The MySQL `TIMESTAMP` is always a point-in-time (they store after conversion to UTC from session zone, and convert back to session zone for presentation). In Presto (and Trino before 427) the MySQL `TIMESTAMP` is mapped to Trino/Presto `TIMESTAMP` which is not point-in-time, it's local time. So if you select such column from two Presto servers running in different JVM zones the returned value can be different (e.g. if the value happens to lie in DST gap in one of the JVM zones).

To fix this issue in Trino we mapped MySQL `TIMESTAMP` (point-in-time behaviour) to Trino `TIMESTAMP WITH TIME ZONE` which more closely matches the point-in-time preserving behaviour. The difference is that `TIMESTAMP WITH TIME ZONE` returns with UTC zone since that's the zone MySQL stores the value in. To convert it to other zone if you want for presentation purposes you need to use `AT TIME ZONE`.

In your example the UTC value and the `AT TIME ZONE` value represent exactly the same point in time, it's just that it's written differently.

**Comment by hashhar** [comment]
So if you want to get values in local zone, use `DATETIME` in MySQL which doesn't have concept of timezone. `TIMESTAMP` in MySQL means UTC time.
