### ISSUE TITLE
Support GROUP BY predicate pushdown when using json_extract in aggregation

### ISSUE THREAD

**Issue by tontinton** [trinodb/trino#23996]
The following queries don't hit my connector's `applyAggregation` breakpoint:

```sql
SELECT max(timestamp) FROM catalog.default.table GROUP BY json_extract(some_str, '$.some_number');

SELECT max(json_extract(some_str, '$.some_number')) FROM catalog.default.table GROUP BY timestamp;
```

**Comment by hashhar** [comment]
For the 2nd query the reason is because if you look at the plan you'll notice some plan node between the aggregation and the table scan.

And the aggregation pushdown rule requires no intermediate plan nodes to be present.

For the first example it's not going to happen anyway because the grouping key is not a column reference.

**Comment by hashhar** [comment]
I'm closing this as duplicate.

Duplicates https://github.com/trinodb/trino/issues/4171.
