### ISSUE TITLE
Support Parquet page filtering using page level column indexes

### ISSUE THREAD

**Issue by ryanrupp** [trinodb/trino#403]
Parquet added support for column indexes which track min/max stats for each underlying page of data (default page size is 1MB) which can be leveraged to skip pages within the column (similar to how ORC row group/stride stats are leveraged I believe). See the parquet format commit here https://github.com/apache/parquet-format/commit/f1de77d31936f4d50f1286676a0034b6339918ee for reference which includes a spec design page [here](https://github.com/apache/parquet-format/blob/54e6133e887a6ea90501ddd72fff5312b7038a7c/PageIndex.md). The Parquet Java library then adds support for this in 1.11.0 for both read/writes, see [here](https://github.com/apache/parquet-mr/commit/e7db9e20f52c925a207ea62d6dda6dc4e870294e) - that's a squashed commit which also includes [filtering](https://github.com/apache/parquet-mr/pull/509/files) support although I believe Presto reader path has split enough from the Parquet library reader that this would be something that is implemented then within `presto-parquet`.

**Comment by tooptoop4** [comment]
1.11 is released

**Comment by tooptoop4** [comment]
https://github.com/prestosql/presto/pull/2333

**Comment by boazberman** [comment]
Any progress about this?

**Comment by JamesRTaylor** [comment]
Couple of questions on this one:

1. Would implementing this require a complete rewrite of the current parquet reader, or could it be done on top of the existing one, @martint?
2. Would writes coming through Presto already have this page level information written or would changes be required on the write side as well?
3. Has there been any uptake of this capability in other products like Hive and Spark? I haven't seen any movement on https://issues.apache.org/jira/browse/SPARK-26345, but perhaps others have more visibility? Most of our writes come through these products, so that's an important factor.
4. Is there an easy way to compute the amount of CPU that was consumed during scanning data (i.e. a metric published out on the EventListener, for example)? This would allow us to determine an upper bound on the ROI of implementing this feature. 

cc. @ryanrupp

**Comment by martint** [comment]
> 1. Would implementing this require a complete rewrite of the current parquet reader, or could it be done on top of the existing one, @martint?

It might be possible, but it wouldn't be a trivial task. FWIW, I'm working on a rewrite of the Parquet reader already, and I plan to add support for this.

> 2. Would writes coming through Presto already have this page level information written or would changes be required on the write side as well?

Only when using the non-Presto-native parquet writer. Supporting this with the native writer would also be another project.

> 4.Is there an easy way to compute the amount of CPU that was consumed during scanning data (i.e. a metric published out on the EventListener, for example)? This would allow us to determine an upper bound on the ROI of implementing this feature.

Not perfectly. You can see the CPU used by the Scan+Filter?+Project? operation by looking at the operator stats in the QueryCompletion event, but there's no way to break that down further and know how much was spent in each of the operations.

**Comment by martint** [comment]
Fixed by https://github.com/trinodb/trino/pull/7349
