### ISSUE TITLE
Skip empty plugin directories

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#4164]
We can skip empty plugin directories in `PluginManager` as these are clearly not plugins.

**Comment by findepi** [comment]
This would solve https://github.com/prestosql/presto/issues/4122.

However, I am not convinced this is a good idea to ignore empty folders.
They do not serve any purpose in Presto installation, so this would be
an "extension point" which we should evaluate carefully.

As a consequence, we would ignore folders containing only README files,
or only non-jar files, and then we would ignore plugin folders `mysql/presto-mysql.zip`,
masking deployment problems.

I would prefer we do not do this.

**Comment by hashhar** [comment]
I'm with @findepi on this once since during our initial attempts at installing custom plugins our build step created directories but the copy command failed and the server helpfully told us so on startup.

This will become a bigger problem once you consider that each worker can have different state of directories. ie. if I copy a JAR to directory on 1 worker but not on other it helpfully fails today whereas it would lead to a difficult to chase deployment issue if we ignore empty directories.

The linked issue could be attributed to bad RPM tooling but I haven't yet seen any justification to allow empty dirs.

**Comment by hashhar** [comment]
Closing since we aren't convinced it's a good idea to allow this and there haven't been asks for this.

@electrum Please reopen if you believe this is still useful to have with some justification why.
