### ISSUE TITLE
Password Authenticator support http connection

### ISSUE THREAD

**Issue by melin** [trinodb/trino#4488]
presto support multiple client connections, in which the tableau version of the earlier version, inconvenient configuration https, can have a switch, support http connection mode. Similar mysql have parameter useSSL.

**Comment by hashhar** [comment]
Trino JDBC driver has `SSL` connection property similar to MySQL `useSSL`. See https://trino.io/docs/current/client/jdbc.html#connection-parameters for reference.
I think the issue you ran into is probably that Trino disallows doing authentication when SSL is not used for security reasons since without SSL the credentials are available in plaintext over the network.

There are ways to allow Trino to allow authentication even without SSL but it's not a good idea.
