### ISSUE TITLE
Support LISTAGG aggregation function

### ISSUE THREAD

**Issue by martint** [trinodb/trino#4835]
```
<listagg set function> ::=
  LISTAGG <left paren> [ <set quantifier> ] <character value expression>
      <comma> <listagg separator> [ <listagg overflow clause> ] <right paren>
      <within group specification>

<listagg separator> ::=
  <character string literal>
<listagg overflow clause> ::=
  ON OVERFLOW <overflow behavior>

<overflow behavior> ::=
  ERROR
  | TRUNCATE [ <listagg truncation filler> ] <listagg count indication>

<listagg truncation filler> ::=
  <character string literal>
<listagg count indication> ::=
    WITH COUNT>
  | WITHOUT COUNT>
```

```
11) If <listagg set function> is specified, then:
    a) The <listagg set function> shall not contain a <window function>, a <set function specification>, 
       or a <query expression>.
    b) If DISTINCT is specified, then the <character value expression> is an operand of a grouping operation. 
       The Syntax Rules and Conformance Rules of Subclause 9.12, “Grouping operations”, apply.
    c) If <set quantifier> is not specified, then ALL is implicit.
    d) It is implementation-defined whether the declared type DTLA of the result is a variable-length character 
       string with implementation-defined maximum length or a character large object type with implementation-defined 
       maximum length. Let MLRT be the maximum length of DTLA.
    e) Let LAS be the <listagg separator>. The length in characters of LAS shall be less than or equal to MLRT.
    f) If <listagg overflow clause> is not specified, then ON OVERFLOW ERROR is implicit.
    g) If <overflow behavior> specifies TRUNCATE and <listagg truncation filler> is not specified, then let LTF be '...'; 
       otherwise, let LTF be the <listagg truncation filler>. The length in characters of LTF shall be less than or equal to MLRT.
```

**Comment by findinpath** [comment]
I'd like to try to implement this functionality.

**Comment by martint** [comment]
@findinpath , go for it! Let me know if you need any guidance.

**Comment by findinpath** [comment]
I am analyzing the code and found out so far: 

- `io.trino.operator.scalar.ConcatFunction` which works for aggregating slices
- `io.trino.operator.aggregation.LongSumAggregation` which works for summing long values

For this feature I'd actually need an "aggregation function" which somehow combines the functionality of the previously evoked functions.
To be more precise, I'd need something like  `java.util.StringJoiner#add` and `java.util.StringJoiner#toString` where the inputs of the aggregation are added to a list/array and are actually joined only in the output phase.


Do you have any hints where to look for an aggregation function on strings in the `trino` code?

**Comment by martint** [comment]
`array_agg` may be closer to what you need for this. Take a look at `ArrayAggregationFunction`

**Comment by findinpath** [comment]
I have a very early  draft for this functionality in this PR

https://github.com/trinodb/trino/pull/7992

I am a bit stuck though because of the following reasons:


In the following sample SQL query:

```
SELECT LISTAGG(value1, ',' ON OVERFLOW TRUNCATE '....' WITH  COUNT) WITHIN GROUP (ORDER BY value2) 
...
```

can be observed that the `LISTAGG` function call  takes a few more parameters than the normal Trino SQL function calls.

Now I could tweak the method `io.trino.sql.analyzer.ExpressionAnalyzer.Visitor#visitFunctionCall` to create a `io.trino.sql.tree.FunctionCall` instance that takes:

- "TRUNCATE"
- "..."
- "WITH COUNT" 

as parameters for the aggregation, so that they can be used within `input`/`combine`/`output` methods of the `io.trino.operator.aggregation.listagg.ListaggAggregationFunction` aggregation function, but I am not sure that this is the right way to do it.


I'd really appreciate having a few pointers here on how to go further.

**Comment by hashhar** [comment]
Merged as https://github.com/trinodb/trino/commit/4c321a97d1e40a8811821deb4f41005828dd1fb3
