### ISSUE TITLE
Null check pushdown for row type fields in the hive connector

### ISSUE THREAD

**Issue by grantatspothero** [trinodb/trino#4876]
Queries of this form against parquet tables are slow:
```
select count(*) from table where row_field is not null
select count(*) from table where row_field is null
```

Queries of this form against parquet tables are relatively much faster:
```
select count(*) from table where row_field.sub_field is not null
select count(*) from table where row_field.sub_field is null
```

where row_field is a row type and sub_field is a primitive type.

The scan step of the plan for the slow queries look like this:
<img width="564" alt="Screen Shot 2020-08-17 at 4 39 23 PM" src="https://user-images.githubusercontent.com/43971820/90548999-733af400-e153-11ea-98b6-9568203b6879.png">

The scan step of the plan for the fast queries look like this:
<img width="413" alt="Screen Shot 2020-08-17 at 4 39 04 PM" src="https://user-images.githubusercontent.com/43971820/90548998-72a25d80-e153-11ea-9768-0a38a9c47293.png">

This is because the fast queries are benefiting from dereference pushdown to limit the amount of data pulled from the parquet files but the slow queries are not. 

See this thread for more details: https://prestosql.slack.com/archives/CGB0QHWSW/p1597699611461100

**Comment by hashhar** [comment]
I don't get how this can be implemented.

Given a row type `r ROW(x BIGINT, y BIGINT, z BIGINT)` and a predicate `r IS NOT NULL` how does the engine know that `r.x IS NOT NULL` is equivalent.

Also generally I don't think they are equivalent either since each partition's schema can be different hence output for `r IS NOT NULL` can differ from `r.x IS NOT NULL`.

Closing due to ambiguity, feel free to re-open if I missed something.
