### ISSUE TITLE
IntegerNumberToVarchar coercer doesn't respect Varchar bounds

### ISSUE THREAD

**Issue by hashhar** [trinodb/trino#5015]
From https://github.com/prestosql/presto/pull/4426#discussion_r478373096:

In Hive connector a coercion like `INTEGER 12345` to `VARCHAR(1)` produces `12345` instead of the expected `1` according to Hive 3.1 semantics.

Another point open to discussion is whether a coercion like `INTEGER -12345` to `VARCHAR(1)` should produce `-` (matching Hive 3.1) or is it worth it for Presto to aim for more sane coercion behaviour.

cc: @findepi @martint @electrum @losipiuk

**Comment by sopel39** [comment]
What does SQL standard says about these?

**Comment by findepi** [comment]
Closing in favor of https://github.com/trinodb/trino/issues/552

**Comment by findepi** [comment]
Reopening. #552 is about CASTs in engine. This issue is about equivalent, but separate, mechanics in Hive connector.

**Comment by hashhar** [comment]
IMO we should just disallow such coercion.

Just for the sake of being compatible with Hive adding this "misfeature" sounds questionable as showcased by the example in the opening comment.

It leads to meaningless coercions e.g. `INTEGER -12345` to might become `-`.
And I don't think anyone should be using or relying on such coercions.

**Comment by martint** [comment]
> What does SQL standard says about these?

The SQL standard doesn't allow those kinds of conversions.

**Comment by findepi** [comment]
This is about behavior internal to the Hive connector, so it's at best governed by "Hive reference impl".
The SQL standard doesn't matter.

**Comment by dain** [comment]
@findepi  Oh that makes sense… yes we need to follow Hive here

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/14179 adds checks in `IntegerNumberToVarchar`, so it no longer produces corrupted data (varchar values exceeding varchar type bounds).

It doesn't make Trino compatible with Hive, as Hive truncates (as described in this issue's description). But I don't think it matters in practice. Anyway, now the problem will be apparent (instead of being silent correctness issue), and we may later decide to align the behavior.

For now, it sounds like no actual users need this.
