### ISSUE TITLE
Final operators stats are not always propagated

### ISSUE THREAD

**Issue by sopel39** [trinodb/trino#5172]
Looking at: `io.prestosql.operator.DriverContext#finished`, it seems that driver might be set as done while it's stats are still not populated into pipeline stats (`pipelineContext.driverFinished(this);` happens after). This might mark task as finished (and final task info set) with driver stats lost.

Relates to: https://github.com/prestosql/presto/issues/5120

**Comment by sopel39** [comment]
cc @dain

**Comment by findepi** [comment]
Question is -- are stats "best effort", or guaranteed?

in tests we would want them to be guaranteed, but maybe it's not necessary in general, and additional synchronisation or latency at comnpletion is not warranted?

**Comment by sopel39** [comment]
I'm not sure `DriverContext` is a problem though since it's not marked as `@ThreadSafe` and it seems to be accessed from thread of `TaskExecutor`

**Comment by dain** [comment]
IIRC the DriverContext is supposed to be single threaded.  Maybe the problem is on the code that is reading these.  

@sopel39 can you describe the problem we are actually seeing in these tests?

**Comment by sopel39** [comment]
@dain it looks like stats from not all drivers (pipelines?) are propagated back to coordinator after query is finished.
This causes certain assertions to fail (e.g input row count is less than expected).

**Comment by yansun7** [comment]
In addition to the risk of losing driver stat, driver context clear up is also skipped in that case ([code](https://github.com/trinodb/trino/blob/582af461414448c0bda723e1f5b2c885b4071d1d/core/trino-main/src/main/java/io/trino/operator/PipelineContext.java#L178))
In my test, I've seen cases from heap dump where lots of DriverContext objects are not collected by GC in time due to this issue.

**Comment by sopel39** [comment]
> In addition to the risk of losing driver stat, driver context clear up is also skipped in that case (code)
In my test, I've seen cases from heap dump where lots of DriverContext objects are not collected by GC in time due to this issue.

Would you be able to track the root cause of the issue?

**Comment by yansun7** [comment]
For my case, it's because DriverContext#failed(..) is called before DriverContext#finished() when query is interrupted by exception ([code](https://github.com/trinodb/trino/blob/3267b918a78eedf91b8e29e06b5a4b218858bc10/core/trino-main/src/main/java/io/trino/operator/Driver.java#L458)), thus there's no chance PipelineContext#driverFinished() can be called to remove driverContext.

**Comment by itsinthebag** [comment]
Not sure this is totally related, but in my case, there is operatorSummaries, but operatorInfo is missing sometime. This only happened in TableScanOperator and ScanFilterAndProjectOperator.
correct operatorStats:
![image](https://user-images.githubusercontent.com/67296874/139481185-546ed6c6-df48-4ecb-916b-14e5d632b5d2.png)

missing operatorInfo operatorStats:
![image](https://user-images.githubusercontent.com/67296874/139481316-287d4769-d7a7-444a-81ea-e68a3791ace7.png)

**Comment by dain** [comment]
> Question is -- are stats "best effort", or guaranteed?

They are best effort.  If we can get stats great, but do not add latency to the query.

**Comment by findepi** [comment]
> They are best effort. If we can get stats great, but do not add latency to the query.

i can imagine use-cases where having accurate stats is worth small additional latency. e.g. chargeback.
What additional latency tax this would take?

**Comment by findepi** [comment]
Additional fix https://github.com/trinodb/trino/pull/9913
Follow up cleanup https://github.com/trinodb/trino/issues/9898
