### ISSUE TITLE
Clean up use of HiveType#getType

### ISSUE THREAD

**Issue by aalbu** [trinodb/trino#5451]
The HiveType#getType method is overloaded.  The signatures are: `Type getType(TypeManager typeManager)` and Type `getType(TypeManager typeManager, HiveTimestampPrecision timestampPrecision)`.  The first signature is deprecated and its usages should be removed.  We need to determine which call sites should use the timestamp precision specified in the session and which ones should explicitly use milliseconds.  See https://github.com/prestosql/presto/pull/5283#discussion_r500924864.

**Comment by hashhar** [comment]
I'm closing this since we'll automatically end up cleaning it when addressing deprecation warnings one by one.

For now the simple fix which this issue implies is to use `DEFAULT_PRECISION` in all current usages which might not actually be right anyway.

Feel free to re-open if this is still needed.
