### ISSUE TITLE
Support Iceberg's UUID in the Iceberg connector

### ISSUE THREAD

**Issue by grantatspothero** [trinodb/trino#6663]
When attempting to query an iceberg table with a UUID type field, I get the following error:

```
java.lang.UnsupportedOperationException: Cannot convert from Iceberg type 'uuid' (UUID) to Presto type
	at io.prestosql.plugin.iceberg.TypeConverter.toPrestoType(TypeConverter.java:107)
        ...
```
It looks like there was some (half-baked) support for the UUID iceberg type previously:
https://github.com/trinodb/trino/commit/f336fa4361cb28c5b724e8457f0e5dd7408f968a

Any more context here about why it was removed?

**Comment by findepi** [comment]
@rdblue can you comment whether UUID stays or will go?

**Comment by findepi** [comment]
Relates to: https://github.com/apache/iceberg/issues/1302

**Comment by rdblue** [comment]
We should have a discussion on the Iceberg dev list about this. Now that we support row identifiers, it may make some sense to include this since it is a better way to store UUIDs. On the other hand, if there aren't any engines that will support the type then it may not make sense to keep it.

I'm interested in considering both sides. We haven't fully removed it because I'm not sure whether it's a good idea or not.

**Comment by findepi** [comment]
@rdblue since Trino has builtin UUID type, it can be supported directly.
For engines without UUID type, values can be mapped to a varchar/string (e.g. with canonical "dashed hex" representation).

**Comment by joshthoward** [comment]
I raised the issue in the Iceberg dev list. Let's see where it goes.

**Comment by rdblue** [comment]
The thread on the dev list said that there's consensus in the Trino community to keep UUID. I didn't realize that. Where did that discussion happen and what were the reasons to keep it?

**Comment by joshthoward** [comment]
@rdblue In the dev list I said that there appeared to be a consensus in this issue, based on your and Piotr's comments, not in the community as a whole.

**Comment by findepi** [comment]
I am fine with Iceberg either keeping or removing UUID type, since I am not a user.
As I user, I would probably prefer to have it.

As I Trino engineer, I want Trino to successfully read every valid Iceberg table, and this includes supporting Iceberg UUID type, per https://iceberg.apache.org/spec/#primitive-types.

Am i reading it correctly this is currently "dead code" in the spec that you @rdblue would want to remove? If it is indeed unused, it should be "easy" (all the due process and notifications aside).

**Comment by electrum** [comment]
I agree with @findepi.

I’m not aware of any discussion or consensus in the Trino community about the UUID type in Iceberg. If you are using UUIDs, then having an explicit type is nicer, since the mapping and display is automatic.

While I wouldn’t advocate to add it to the spec as new type, unless we know for certain that it’s not used, deprecating is probably more annoying than keeping it around. And it does have some utility.

I don’t want to be in a situation where we deprecate it, then find out people are using it, and have to support this thing that is marked deprecated and will never actually go away.

My preference is to make a decision to either hard deprecate or support it.

**Comment by rdblue** [comment]
I agree, we should either remove it or support it. I think we just need to decide.

It seems useful to me so I'm leaning toward keeping it. I think if we had good support for UUID in engines, it would be a good type to use for identifiers because you can generate them in parallel without coordination and we can optimize them for use in comparison by keeping them as fixed[16] internally. They aren't as useful as I originally thought, but there are good advantages compared to keeping huge strings for the same purpose.

**Comment by findepi** [comment]
> I agree, we should either remove it or support it. I think we just need to decide.

@rdblue  What's the process to arrive at the decision?
Should i start a thread on the mailing list, or something like that?

**Comment by findepi** [comment]
for the reference, this is also being discussed on iceberg dev mailing list https://mail-archives.apache.org/mod_mbox/iceberg-dev/202107.mbox/browser

**Comment by rdblue** [comment]
Coming to a consensus on the dev list is what we normally do in Apache communities. The discussion there is a good one.

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/8747 adding support for Iceberg UUID in Trino, as this is what we seem to be leaning to.
