### ISSUE TITLE
Trino + Pinot Connector - Lowercasing table name in query

### ISSUE THREAD

**Issue by Nguyen-Kha** [trinodb/trino#6789]
When querying through the Trino CLI for data stored in Apache Pinot (both inside docker container), all query characters are converted to lowercase which causes an issue for querying tables with an uppercase character in its name.

For example, a table in Pinot is called `baseballStats`
When sending this query through the Trino CLI:
`SELECT * FROM baseballStats LIMIT 10;`
Pinot will receive it as:
`select * from baseballstats limit 10`
which will cause an error on the pinot side since the query sent from Trino is being lowercased. 

Is there a way to keep the casing of queries in Trino?

**Comment by hashhar** [comment]
This shouldn't matter since the Pinot connector tries to resolve the name as it appears in Pinot. See https://github.com/trinodb/trino/blob/7fd62db50aec490907e93412441fe65dbfea6052/plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java#L302-L316 for the relevant code-path.

Can you share the full-stack trace (edit the original issue)?

Also, let's continue this discussion on [Slack](https://trinodb.io/slack.html) since you may find other Pinot users there who might have more info.

**Comment by kokosing** [comment]
Is this related to https://github.com/trinodb/trino/issues/17?

**Comment by findepi** [comment]
@hashhar thanks for the link ref. I wasn't aware that Pinot connector does equivalent of `case-insensitive-name-matching` configuration, but unconditionally.

**Comment by ebyhr** [comment]
`getPinotTableNameFromTrinoTableName()` exactly finds the table case-insensitively, but `PinotTableHandle` lowercase it. I assume case insensitive matching isn't working in this connector now.
