### ISSUE TITLE
Migrate Mongo tests to use BaseConnectorTest 

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#7115]
https://github.com/trinodb/trino/pull/6989 introduced new `BaseConnectorTest` test class which replaces `AbstractTestDistributedQueries` and `AbstractTestIntegrationSmokeTest`.

Scope of this ticket is to restructure Mongo test code to follow new pattern.
`TestMongoIntegrationSmokeTest` should be merged with `BaseMongoDistributedQueries` to form `BaseMongoConnectorTest`
Then on top of that we should create  `TestMongoConnectorTest`, `TestMongo3LatestConnectorTest` and `TestMongo4LatesConnectorTest` (removing `TestMongoDistributedQueries`,`TestMongo3DistributedQueriesLatest` and `TestMongo4DistributedQueriesLatest`)

Please ensure that `BaseMongoConnectorTest` is created as a rename of `TestMongoIntegrationSmokeTest` so we keep as much Git history as possible.

A PR which restructures MySQL tests is a good reference:  https://github.com/trinodb/trino/pull/7011

**Comment by JoJoBizarreAdventure** [comment]
Hi! I'm interested in solving this issue for learning how to contribute in Github. Could you please assign this issue to me? I want to have a try.

**Comment by losipiuk** [comment]
Thanks @JoJoBizarreAdventure . Assigned.

**Comment by JoJoBizarreAdventure** [comment]
Sorry for waiting for such a long time, I'm busy for a while for looking for an internship. 
I'm working on this issue now and already send email asking for verification. 
But I'm wondering if I misunderstood the requirement. 
![image](https://user-images.githubusercontent.com/64888038/115110567-acf81f00-9fae-11eb-9755-5d0e8e7ca0e4.png)
I found that there is no file named **TestMongo3DistributedQueriesLatest**  and **TestMongo4DistributedQueriesLatest**.
So I wonder if there is some changes? Please give me more instructions on this, thanks.

**Comment by hashhar** [comment]
@JoJoBizarreAdventure If I understand @losipiuk's intent correctly then you should:

1. Remove `BaseMongoDistributedQueries` by merging it into `TestMongoDistributedQueries` (because it's the only class that extends from `BaseMongoDistributedQueries`).
2. Make `TestMongoDistributedQueries` extend `BaseConnectorTest` (which is what this issue is about).
3. Rename `TestMongoDistributedQueries` to `TestMongoConnectorTest`.

The smoke test classes don't need to be changed - the smoke tests are a set of lightweight tests which we use when we want to test different versions because it's wasteful to run in-depth tests against every version/configuration. The `BaseConnectorTest` is a detailed test which we generally run against one of the versions.

**Comment by JoJoBizarreAdventure** [comment]
Thanks @hashhar
