### ISSUE TITLE
ORC ACID DELETE ignores partition filter, deleting too much

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#7290]
```
trino:default> CREATE TABLE nation WITH (transactional=true, partitioned_by=ARRAY['regionkey']) AS SELECT nationkey, regionkey FROM tpch.tiny.nation;
CREATE TABLE: 25 rows
```

```
trino:default> SELECT * FROM nation ORDER BY regionkey, nationkey;
 nationkey | regionkey
-----------+-----------
         0 |         0
         5 |         0
        14 |         0
        15 |         0
        16 |         0
         1 |         1
         2 |         1
         3 |         1
        17 |         1
        24 |         1
         8 |         2
         9 |         2
        12 |         2
        18 |         2
        21 |         2
         6 |         3
         7 |         3
        19 |         3
        22 |         3
        23 |         3
         4 |         4
        10 |         4
        11 |         4
        13 |         4
        20 |         4
(25 rows)
```

```
trino:default> DELETE FROM nation WHERE regionkey = 4 AND nationkey % 10 = 3;
DELETE: 3 rows
```
-- this should have deleted 1 row, not 3

```
trino:default> SELECT * FROM nation ORDER BY regionkey, nationkey;
 nationkey | regionkey
-----------+-----------
         0 |         0
         5 |         0
        14 |         0
        15 |         0
        16 |         0
         1 |         1
         2 |         1
        17 |         1
        24 |         1
         8 |         2
         9 |         2
        12 |         2
        18 |         2
        21 |         2
         6 |         3
         7 |         3
        19 |         3
        22 |         3
         4 |         4
        10 |         4
        11 |         4
        20 |         4
(22 rows)
```

```
trino:default> DELETE FROM nation WHERE regionkey = 4 AND nationkey < 100;
DELETE: 22 rows
```

```
trino:default> SELECT * FROM nation ORDER BY regionkey, nationkey;
 nationkey | regionkey
-----------+-----------
(0 rows)
```

Relates to https://github.com/trinodb/trino/issues/7291 and https://github.com/trinodb/trino/issues/7300

**Comment by findepi** [comment]
cc @djsstarburst

**Comment by djsstarburst** [comment]
I'm guessing the problem is some error handling the `TupleDomain`.  I'm looking into it.

**Comment by findepi** [comment]
This is where pushed down predicates are getting lost:
https://github.com/trinodb/trino/blob/dcb9f8a87bd8ce1d2b3e40f3be927b3e99ce3750/core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java#L234

**Comment by djsstarburst** [comment]
AFAICT, the problem originates in https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java#L265, in method `pushFilterIntoTableScan`.  Here is the offending code:

```
        Expression resultingPredicate = createResultingPredicate(
                metadata,
                domainTranslator.toPredicate(remainingFilter.transform(assignments::get)),
                nonDeterministicPredicate,
                decomposedPredicate.getRemainingExpression());
```

The `decomposedPredicate` has the correct `TupleDomain` specifying `regionKey` in the range [4,4], and a `remainingExpression` which is code for "nationkey % 10 = 3".  But `resultingPredicate` has only the filter for "nationkey % 10 = 3".  It seems like the code above should be using the `decomposedPredicate.getTupleDomain()`, but nothing is using it.

**Comment by djsstarburst** [comment]
The bug arises because `PruneTableScanColumns.pruneColumns()` is called with a DeleteNode on top of a ProjectNode on top of a `TableScanNode`.  The set of assignments in the ProjectNode doesn't contain `regionKey`, and that results in the enforcedConstraint in the TableScan, which depends on column `regionKey`, is pruned, and the resulting `enforcedConstraint` is ALL.  I'm unsure why pruning the constraint in this way is the right thing to do, but the result is a table scan no longer constrained to a specific partition.

The set of `Symbols` that drives pruning comes from the assignments in the parent node.  It seems that if the `TupleDomain` isn't empty, we need to add assignments to the `ProjectNode` under the `DeleteNode` for the columns in the `TupleDomain`.  But this makes me unsure how the filtering ever works, because I don't see it done for other nodes.  Count me confused so far 🤔

**Comment by findepi** [comment]
The bug is the effect of interaction of Row-level delete with `applyFilter` removing Filters that are pushed wholly into TableScan.
`applyFilter` works great, but then, in https://github.com/trinodb/trino/blob/dcb9f8a87bd8ce1d2b3e40f3be927b3e99ce3750/core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java#L234, we replace 'enhanced' TableHandle with the original one, without filters.

**Comment by djsstarburst** [comment]
> The bug is the effect of interaction of Row-level delete with applyFilter removing Filters that are pushed wholly into TableScan.

I put breakpoints at `HiveMetadata.applyDelete()` and `HiveMetadata.executeDelete()`, and they are never called.  beginDelete() and finishDelete() are called, but by the time beginDelete() is called, AFAICT the damage to the table scan is done.

**Comment by findepi** [comment]
same for UPDATE -- https://github.com/trinodb/trino/issues/7300

**Comment by djsstarburst** [comment]
> The root problem is that the TableHandle stored in the DeleteTarget and therefore passed to ConnectorMetadata.beginDelete() isn't the right TableHandle - - the handle that should be passed to beginDelete() is the handle as it exists in the TableScanNode, because that's the handle containing the pushed-down filters.

The solution is to get the `TableHandle` to pass to `ConnectorMetadata.beginDelete()` from the appropriate `TableScanNode` instead of the `DeleteTarget`, and then save the `TableHandle` returned by `ConnectorMetadata.beginDelete()` in the `DeleteTarget`.  The question is how to find the appropriate `TableScanNode`:

- Do a depth-first search of the `DeleteNode` tree, returning the `TableHandle` from the first `TableScanNode` encountered.  I've prototyped that change, and with it the test passes, but it risks finding the wrong `TableScanNode`.
- Use the existing boolean `forDelete` flag, for both DELETE and UPDATE.
- Tag the `TableScanNode` with some unique ID, maybe just a long counter, and save that unique id in the `DeleteNode`, and search only for a `TableScanNode` with that ID.

**Comment by djsstarburst** [comment]
I just posted PR #7307 which fixes this bug for DELETE and UPDATE.
