### ISSUE TITLE
File system access control  base on database like mysql etc

### ISSUE THREAD

**Issue by hqbhoho** [trinodb/trino#7311]
This access control plugin now allows you to specify authorization rules in a JSON file. But file update is not easy than database .

**Comment by kokosing** [comment]
That is quite difficult technically. In order to support database we need JDBC drivers. Notice access control are in Trino core engine and most of the connectors. So if we decide to support PostgreSQL then each such module will gain PostgreSQL driver dependency. If we then decide to add Oracle, then we will have two of them. Drivers usually are well shaded, but is also known that sometimes they like to cause issues.

Also that would require us to handle migration process whenever we change access control (and we do it quite frequently, notice recently added UPDATE and incoming MERGE syntax).

Notice that Trino support refresh period time for access control configuration files so whenever the file is changed, Trino will change its behavior.

Maybe you could in your environment capture authorization policies in a database and them periodically dump them as JSON file for Trino? That way we don't need to deal with different JDBC vendors.

**Comment by hqbhoho** [comment]
> That is quite difficult technically. In order to support database we need JDBC drivers. Notice access control are in Trino core engine and most of the connectors. So if we decide to support PostgreSQL then each such module will gain PostgreSQL driver dependency. If we then decide to add Oracle, then we will have two of them. Drivers usually are well shaded, but is also known that sometimes they like to cause issues.
> 
> Also that would require us to handle migration process whenever we change access control (and we do it quite frequently, notice recently added UPDATE and incoming MERGE syntax).
> 
> Notice that Trino support refresh period time for access control configuration files so whenever the file is changed, Trino will change its behavior.
> 
> Maybe you could in your environment capture authorization policies in a database and them periodically dump them as JSON file for Trino? That way we don't need to deal with different JDBC vendors.
