### ISSUE TITLE
Can Presto use Hive indexes?

### ISSUE THREAD

**Issue by voycey** [trinodb/trino#736]
Previous issue: https://github.com/prestodb/presto/issues/3433

We have a table with 229B rows in it, if we want to issue a count on this table it takes upwards of 30 minutes to return the value. Hive returns the same value instantly.

We are using the Hive catalog - does it not make sense to read the Hive indexes for these tables in this case?

**Comment by ryanrupp** [comment]
The old linked issue is in regards to Hive indexes which appear to be removed in Hive 3.0 in favor of using columnar formats that have their own column level indexes/stats in them, see [here](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Indexing). I think why the query in question for you is fast in Hive though is due to table statistics Hive can track so it's just using those. Guessing the Presto Hive connector doesn't have the logic in it to rewrite queries like this to hit the stats instead of going to the actual files? In the meantime though you can use:

```
show stats for <table>
```
Which could get you the table row count (and other column level stats), see [here](https://prestosql.io/docs/current/sql/show-stats.html). Although maybe there's some value is doing that kind of automatic identification of SQL that could be resolved purely by table stats (sort of niche though I think).

**Comment by dain** [comment]
I would love to be able to use table statistics for query results, but unfortunately Hive does not guarantee that the statistics are accurate.  The best we can do today is to open each file and read the row count from the footers (assuming you are using ORC or Parquet), which is expensive but not nearly as expensive as reading all the data.

BTW, I believe this is something that [Iceberg](https://github.com/Netflix/iceberg) will be able to support.  Iceberg is an alternate to the Hive data layout.

**Comment by voycey** [comment]
When you say "Does not guarantee they are accurate" how does Spark use them? 
We have tasks that update the column statistics as new data is added - would Presto not be able to use these?

Unfortunately we will be coming towards 500B rows in our table in the next couple of months - this would equal around an hour to do a simple count.

@dain - the ORC footers are stored in the metastore during ANALYSE queries are they not? Could they be read from there rather than from the file each time?

**Comment by electrum** [comment]
I'm not familiar with what Spark does. If they always use metastore stats, then they are returning incorrect answers whenever the stats are wrong. Presto could have an option to assume they are correct, but you would need to opt-in to that configuration, since we believe that correctness is of utmost importance for a database.

ORC footers do store stats and Presto will utilize them for certain operations. For example, the following query will only read the file footer:

```sql
SELECT count(*) FROM example
```

ORC footers are not stored in the metastore. The metastore has its own statistics which are similar but not the same.

Can you share the query that is taking 30 minutes?

**Comment by voycey** [comment]
Its a simple `count(*) ` query, we have a lot of files, a fair few partitions and a LOT of data. I think as Dain said above it is having to read through the ORC footers on each file.

There is this on the Hive confluence page: https://cwiki.apache.org/confluence/display/Hive/StatsDev

> When Hive metastore is configured to use HBase, this command explicitly caches file metadata in HBase metastore.  
> 
> The goal of this feature is to cache file metadata (e.g. ORC file footers) to avoid reading lots of files from HDFS at split generation time, as well as potentially cache some information about splits (e.g. grouping based on location that would be good for some short time) to further speed up the generation and achieve better cache locality with consistent splits.
> 
> ANALYZE TABLE Table1 CACHE METADATA;

Probably a poor assumption to make that this would be carried over for a MySQL based Metastore? 

Caching ORC file footers would be pretty big benefit I think - Object storage is "slow", the metastore needs to know about these partitions anyway in order to offer them up to Presto - so why not have these stored? (we exclusively use Hive as the catalog - is there a better way?)

**Comment by voycey** [comment]
https://issues.apache.org/jira/browse/HIVE-12075

I see in the comments that this was never shipped as they removed the HBase functionality - I guess that answers that!

**Comment by electrum** [comment]
Can you give a full example query? Does it have any filters? Any filters on non-partition columns?

Also, can you explain more about the high level problem? How and why you are running these queries, etc. I’m wondering if there might be alternative solutions.

**Comment by voycey** [comment]
The query is part of another process from VerdictDB (Cardinality estimation engine) - the first step is to simply do `select count(*) from table` to get the total number of rows - this takes 30 mins+ as Presto has to read through the 4.19 Million ORC files we have in our data warehouse (~30TB). 

In Hive this is instant as it stores partition information from the ANALYSE commands we run on data ingestion.

The High level problem is simply the time that it is taking to do this is adding at least 30 mins onto each process we have to run on the table (I don't have full details but I believe it might have to do this several times).

For now we are running things directly through Hive and are using Presto to just run queries but anything that involves a full count (much of our stuff does at some point) is painful with this much data.

**Comment by electrum** [comment]
Is it possible to run a different query? Today, you can query stats directly in Presto using the `SHOW STATS` command. We could have the Hive connector expose the row count directly as a hidden table, similar to the existing `$partitions` table:
```sql
SELECT row_count FROM "orders$row_count"
```
Or have a `hive.system.table_stats` table with statistics for all tables (though it would be slow to query without filters as stats have to be fetched from the metastore individually per table).
