### ISSUE TITLE
Document to_base64url function

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino#7693]
Exists in list but missing info and link

**Comment by SivaTharun** [comment]
@mosabua i am a newbie to open source contribution, can i start working on this issue.

**Comment by mosabua** [comment]
Yes .. have a look at the readme file in the docs folder to see how it works and then potentially assign this issue to yourself and submit a PR.

**Comment by Damans227** [comment]
@SivaTharun Hey Siva! How are you ? Just touching base with you to check if you are working on this one. Lemme know if you have any questions.

**Comment by SivaTharun** [comment]
Thanks @Damans227 for reaching out, i have started working on this PR, will raise a PR on this in a day or two.

**Comment by Damans227** [comment]
> 
> 
> Thanks @Damans227 for reaching out, i have started working on this PR, will raise a PR on this in a day or two.

Cool! Lemme know if you may have any questions or concerns. Goodluck 👍🏽

**Comment by SivaTharun** [comment]
@mosabua can you review this [PR](https://github.com/trinodb/trino/pull/7860), that i have raised for this issue, i had to close the previous PR, as the author is taken as root user of my machine and i missed adding git global credentials.
i have already signed the cla document as mentioned in  the [read me].(https://github.com/trinodb/cla/blob/master/README.md)

please add me to the list of contributors so that, the CLA sign check passes.

**Comment by mosabua** [comment]
PR is merged. Well done.
