### ISSUE TITLE
How to use Trino exposed API due to permission issues

### ISSUE THREAD

**Issue by chenshaojin** [trinodb/trino#7804]
request: curl http://127.0.0.1:8080/ui/api/stats
response: Unauthorized

**Comment by hashhar** [comment]
this is expected since the APIs under `/ui/` are not public API.
So some of them can require authentication, others can require cookies while others may be public.

`/ui/api/stats` requires valid authentication. So for example if Trino UI is configured with password auth then HTTP basic auth headers need to be present, if using OAuth2 then a Bearer token needs to be present and so on.
