### ISSUE TITLE
[flaky] trino-main module tests time out

### ISSUE THREAD

**Issue by lukasz-walkiewicz** [trinodb/trino#7805]
A few of the most recent hits:
https://github.com/trinodb/trino/runs/2464394675
https://github.com/trinodb/trino/runs/2455585750
https://github.com/trinodb/trino/runs/2442284867

**Comment by kokosing** [comment]
Successful trino-main takes about `succeeded 13 hours ago in 54m 15s`, so there is small space for error. I think we should try to either remove not needed tests execution or split this into two jobs.

**Comment by martint** [comment]
I believe this is due to https://github.com/trinodb/trino/pull/7751

Previously, the mbeans were exported only on calls to `PlanOptimizers.initialize()`, which was done by Guice, and only in the context of server instantiation. In LocalQueryRunner, `PlanOptimizers` is instantiated for every test (see `LocalQueryRunner.getPlanOptimizers()`). This is causing tests to spend the majority of time exporting mbeans now.

<img width="1497" alt="Screen Shot 2021-04-29 at 3 44 59 PM" src="https://user-images.githubusercontent.com/14387/116627383-e2333400-a901-11eb-9ee6-c4431227309b.png">

**Comment by martint** [comment]
https://github.com/trinodb/trino/pull/7810
