### ISSUE TITLE
Chained view performance

### ISSUE THREAD

**Issue by raftAtGit** [trinodb/trino#7976]
In this [stackoverflow answer](https://stackoverflow.com/a/56679790/3134813), it's mentioned that:

> Presto view is always as fast as querying underlying table. This is because a view is replaced with its defining query during query planning time.

Does this also apply to chained views? I mean views backed by other view(s) which in turn backed by other view(s).

In this case, is the view replaced with its defining queries down to top level?

**Comment by hashhar** [comment]
View definitions are recursively expanded to the base table.
You can verify this by running an `EXPLAIN` on the  query.

As far as performance is concerned the planning might take more time as the depth of the chain increases because Trino needs to talk to the Hive metastore for getting the view definitions and it cannot fetch the next definition until  the current one is resolved. However it shouldn't be a noticeable difference. Execution times are unaffected because the final execution plan is the same.

Feel free to join our [Slack](https://trino.io/slack.html) to ask questions and continue the conversation there.
