### ISSUE TITLE
Set default time zone for current session

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#8112]
```
SET TIME ZONE <set time zone value>


<set time zone value> ::=
    <interval value expression>
    | LOCAL
```

<img width="1231" alt="set_time_zone_specification" src="https://user-images.githubusercontent.com/57260417/119889883-6bf11400-bf37-11eb-84c8-850f5d3c6dbe.png">

**Comment by findinpath** [comment]
Reference implementations:
- `io.trino.execution.UseTask`
- `io.trino.execution.SetSessionTask`
- `io.trino.execution.SetPathTask`

**Comment by findepi** [comment]
Protocol-wise, introducing a new header for `SET TIME ZONE` will mean that clients need to be updated to support that.
OTOH, we already have `Trino-Time-Zone` header, which client use to send time zone information to the server.

Technically possible options

- introduce `Trino-Set-Time-Zone` header for conveying response from `SET TIME ZONE` back to the client.
   - this should come with `Trino-Client-Capabilities` detection, so that the task fails when client does not support that.
      otherwise statement would silently have no effect (correctness).
- introduce e.g. a session property that would override `Trino-Time-Zone`. That would mean clients don't need to be updated.
  - note that we have `sql.forced-session-time-zone` feature, where already override `Trino-Time-Zone` sent by the client
 
 cc @electrum @hashhar @joshthoward

**Comment by findinpath** [comment]
Linked issue for the `sql.forced-session-time-zone` setting: #1164

**Comment by findinpath** [comment]
I created a draft PR by taking into account the second suggestion from @findepi  which uses behind the scenes a session property to store the default time zone for the SQL session.
