### ISSUE TITLE
Does Trino Support S3 File Storage For Metastore?

### ISSUE THREAD

**Issue by chadleeshaw** [trinodb/trino#8193]
In the old prestosql I was able to use the hive connector to create a hive metastore catalog directory as s3://warehouse(see below).  The only options for the metastore I'm seeing in the docs are Thrift and glue.

```
    connector.name=hive-hadoop2
    hive.metastore=file
    hive.metastore.catalog.dir=s3://warehouse/
```

**Comment by hashhar** [comment]
The file hive metastore is only used for testing the connector itself and it's not meant to be used in production.

It doesn't implement all metastore operations, cannot be used concurrently and one version of Trino may not be able to read the file created by a different version of Trino.

Trino still has it but the reason it's not documented is because it isn't fit to be used anywhere except the test suites in Trino.
