### ISSUE TITLE
Implement BYTE_STREAM_SPLIT encoding for Parquet

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#8357]
See https://github.com/trinodb/trino/pull/8338

**Comment by manupatteri** [comment]
I wanted to take a look at this. I wanted to reproduce this first. I could generate a parquet file where float column was in BYTE_STREAM_SPLIT encoding. Now I want to know what are the connectors which support parquet. I could identify Hive and iceberg only, as they are the ones which supports generic files/filesystems. Other databases have their own format.  
Now in iceberg I couldn't find support for external table. Basically I have to configure  the table to be parquet format. Since Trino doesn't support this encoding on write  path I can't generate this encoding without modifying existing code.  So is Hive the only option I have for reproducing it with minimal effort?

**Comment by manupatteri** [comment]
I had a PR in this state for for some time. Just wanted to get it out and get early feedback. I think I should probably add some more tests for Float type. Also I have sort of replicated test classes. May be I should templatize them to avoid repeating tests.

**Comment by skrzypo987** [comment]
Don't want to ruin the party but do we know if implementing this brings any performance benefit?
These encodings are not widely used as they require a lot of single-byte memory copying with little compression ration benefit.

**Comment by raunaqmorarka** [comment]
> Don't want to ruin the party but do we know if implementing this brings any performance benefit?
> These encodings are not widely used as they require a lot of single-byte memory copying with little compression ration benefit.

As per the original parquet issue https://issues.apache.org/jira/browse/PARQUET-1622, this makes float/doubles compress better. Maybe benefit of reduced IO can make the additional CPU effort worth it, but that may or may not be worthwhile trade-off depending on the setup and workload. IMO the main reason to implement it would be compatibility with the parquet spec and ability to read such data just in case some other engine has produced it.

**Comment by skrzypo987** [comment]
I agree. Let's just provide some sort of benchmark mid-work to be aware of how this trade-off work
