### ISSUE TITLE
How can I get query performance statistics

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#8606]
I want to get all the finished running query's  performance statistics such as elapsedTime. I found /v1/query can get the 100 query's running details but I want to get the incremental query's statistics by date time filter and also user filter.

**Comment by hashhar** [comment]
Generally people implement the Event Listener SPI (https://trino.io/docs/current/develop/event-listener.html) for this since it includes all the information you'd want.

You can write the events to whereever you want (RDBMS, Kafka etc.) and make use of them.
Note that it's not possible for the co-ordinator to hold information for a large number of queries because everything is in-memory and the more queries you try to save the less memory is available for the actual query planning and scheduling.

Closing since this is not an "issue" within Trino itself. Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.

**Comment by njalan** [comment]
@hashhar  Thanks for your reply. Does this event listener spi support prestosql 340?

**Comment by ebyhr** [comment]
@njalan Yes, it's supported in version 340.

**Comment by njalan** [comment]
@ebyhr Got it,Thanks
