### ISSUE TITLE
Logout in Web UI does not working using oauth2

### ISSUE THREAD

**Issue by kaojunsong** [trinodb/trino#8672]
Hi exports,

I am using keycloak for the oauth2 implement for trino, and I configure the trino config.properties according to https://trino.io/docs/current/security/oauth2.html.

And I can login to the trino Web UI successfully , but when I try to logout using the green "Log Out" button, I can't logout, and I'm  still in the Web UI page.

**Comment by kokosing** [comment]
CC: @lukasz-walkiewicz

**Comment by kaojunsong** [comment]
@lukasz-walkiewicz Hi, could you please have a look at this issue? Does trino have the logout function for oauth2? If yes, is this a bug?

**Comment by kokosing** [comment]
It is a bug. Please notice the labels. The problem is that it depends on what IdP you are using. TBH we haven't done much testing with keycloak yet. So it is more a question of what IdP are supported. We test quite frequently with Okta, Hydra, ADFS. Once we did testing for Auth0.

**Comment by aakashnand** [comment]
I am using Oauth with Azure and in my case Logout is working fine. when I click logout button I am redirected to login screen of Azure

**Comment by kaojunsong** [comment]
@aakashnand thanks for your information, have you any configurations for logout?  Or just the configurations in https://trino.io/docs/current/security/oauth2.html?

**Comment by aakashnand** [comment]
@kokosing Sorry, I remember I had tweaked something it was like 2-3months ago and now I just tested it again and it is not working. I will find more and will let you if I find the solution

**Comment by lukasz-walkiewicz** [comment]
Hi @kaojunsong,

Could you take a look at browser's network log (Developer Tools > Network) while clicking `Log out` button to confirm that the actual logout is not happening?

**Comment by kaojunsong** [comment]
@lukasz-walkiewicz Hi, thanks a lot for your response.
I say there is logout request sent:
![image](https://user-images.githubusercontent.com/9572722/130042352-3848d33d-e641-4f56-b6b3-518403cc97ca.png)

**Comment by lukasz-walkiewicz** [comment]
It looks like the logout on the Trino side is actually happening (notice `__Secure-Trino-OAuth2-Token=delete`) but since Trino does not have any page a user could be redirected to after a successful logout and the user starts the authorization flow right away. If he/she is still logged in the IdP (in your case Keycloak) the authorization flow succeeds without the user even noticing it.
That said, of course the user experience could be better in this area and providing a simple logout page (similar to `/successful.html` or `/failure.html`) would improve it.
