### ISSUE TITLE
iceberg connector access s3 occures TCP RST error

### ISSUE THREAD

**Issue by simple-tec** [trinodb/trino#8851]
HI: 

I use trino358, the iceberg connector configurations are: 
etc/catalog/iceberg.properties:
```
connector.name=iceberg
hive.metastore.uri=thrift://172.21.81.147:9083
hive.s3.endpoint=http://172.21.81.147:9001
hive.s3.aws-access-key=minio
hive.s3.aws-secret-key=minio123
```

On trino CLI, I create schema and table as follow:
```
trino> CREATE SCHEMA iceberg.demo
WITH (
location = 's3a://jinxin/'
);
trino> CREATE TABLE iceberg.demo.test ("id" INT,"content" VARCHAR);
```

so far, all is ok.then i insert one data as follow: 
```
trino> INSERT into iceberg.demo.test VALUES (10,'XD');
```
This insert command runs successfully. but It took about 0.8 second, which is too long. 
I began to explore why the insert is so slowly.
When i sniff the packages between trino server and s3(i use minio), i find the abnormal condition: 
**trino sends TCP RST package occasionally, which will close the socket connect and reconnect, the reconnection takes time.**
![image](https://user-images.githubusercontent.com/74649647/129004319-b2458059-4429-457d-9e4b-c3c02cf65938.png)

Could you please give me some advise to improve this ?

The attachment is wireshark pcap file:
[trino.tar.gz](https://github.com/trinodb/trino/files/6967249/trino.tar.gz)

**Comment by hashhar** [comment]
this is possibly same as https://trinodb.slack.com/archives/CGB0QHWSW/p1706261045943349?thread_ts=1701227423.866509&cid=CGB0QHWSW

Quoting relevant parts here:

> what’s the exact sequence you’re seeing with the SYN -> RST trace? Is it SYN -> RST + ACK? That suggests something very fundamental going on at the connection management level. AWS support should route this to the S3 team to see if they have any logs on their side about those requests, but since this only affects the v2 SDK client (is that still a correct assumption?) there might be something about the client’s behavior that we can adjust to avoid the issue

> [@david](https://trinodb.slack.com/team/UFN62KDEU)
 if the TCP trace sequence is SYN -> RST + ACK then that’s what you would expect to see when you try to establish a new connection to a host that no longer has a process listening on that port or otherwise is hard rejecting the connection attempt. That could be something that you would see if the S3 service host you’re communicating with is being retired or restarted, but in that case you would expect the client to retry to one of the other IP addresses resolved for S3 (S3 DNS lookups generally respond with 4 IP addresses). It could be that the V2 client is attempting to connect to the same IP repeatedly on connection failure and that behavior may be different than the V1 client which may attempt to re-resolve the host in that situation (not sure). In either case, the S3 service logs might shine more light on why exactly the connection is rejected and a deeper dive into the V1 and V2 SDK client source might shine some more light on whether the DNS resolution behaviors on failure are different between the two

> [@david](https://trinodb.slack.com/team/UFN62KDEU)
 the S3 problem seems to be gone for good in v439 - even without using one of your re-implemented S3-related properties.

This used to happen more with SDK v1 because of https://issues.apache.org/jira/browse/HTTPCLIENT-1610. There's some workarounds there.

So since Trino 439 this shouldn't be a problem.

Please re-open if you still see this.
