### ISSUE TITLE
Trino is losing out numeric columns from postgresql

### ISSUE THREAD

**Issue by ikumarvinod** [trinodb/trino#9099]
I am using Postgresql Connector. 
My table has two numeric fields
Both the column is dropped in the trino queries.

**Comment by hashhar** [comment]
See https://trino.io/docs/current/connector/postgresql.html#decimal-type-handling

Numeric/Decimal columns with undefined scale/precision need to be mapped to a default scale and precision using configuration properties.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there - it'll get you quicker help because more people are there.

**Comment by findepi** [comment]
I will close this as answered.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://trino.io/slack.html).
