### ISSUE TITLE
pushdown queries not working on data source (sql server) with one or more joins

### ISSUE THREAD

**Issue by marcejohnson** [trinodb/trino#9347]
I am running latest PrestoDB (Release 362 - 20 Sep 2021) as of this writing on OSX.
It is installed using the recommended configs per the [trino deployment documentation](https://trino.io/docs/current/installation/deployment.html).

When I query against a single data source (Microsoft SQL server) with one or more joins I am not seeing pushdown queries work.  That is, it is not efficient and I see table scans.

For example:
```
SELECT a.email1, address1 FROM sqlserver.dbo.tb_address a 
       JOIN sqlserver.dbo.tb_cust_address ca ON ca.address_id = a.address_id
       WHERE a.email1='test.user@yourcompany.com';
```
Result performs a table scan of 1.36M rows:
```
Query 20210923_110056_00010_sw5uc, FINISHED, 1 node
Splits: 66 total, 66 done (100.00%)
3.58 [1.36M rows, 0B] [379K rows/s, 0B/s]
```
Note: all the fields referenced in the latter query **are** indexed.

If I remove the join then it does **not** perform a table scan.
For example:
```
SELECT email1, address1 FROM sqlserver.dbo.tb_address 
       WHERE email1='test.user@yourcompany.com';
```
Which results in no table scans (better efficiency):
```
Query 20210923_110326_00011_sw5uc, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
1.38 [1 rows, 0B] [0 rows/s, 0B/s]
```
What am I doing wrong, or misunderstanding?
Is there a non-default `config.properties` setting to enable pushdown for this?
Thanks in advance!

**Comment by hashhar** [comment]
You need to set the config property `join-pushdown.enabled` to true to enable join pushdown. It's not enabled by default because some joins can cause more data to be read in case of pushdown vs without pushdown (e.g. JOIN that results in more output rows than input).

There is also a session property you can set to enable it for some queries/temporarily - `SET SESSION sqlserver.join_pushdown_enabled = true`.

I do notice that the config isn't mentioned outside of the 353 release release notes - will document it and submit a PR for that.

Feel free to join our [Slack](https://trino.io/slack.html) and continue the conversation there.
