### ISSUE TITLE
Create table as from Druid Catalog

### ISSUE THREAD

**Issue by DwijadasDey** [trinodb/trino#9411]
Is it possible to create a new table from Druid catalogue using `CREATE TABLE tab1 AS SELECT * FROM TABLE1` syntax ?

I am getting `"This connector does not support creating tables with data" `error when i try to create table fro Druid catalogue.

```
trino:druid> CREATE TABLE cdc_fnd_logins_trino
          -> AS
          -> select * from "druid".cdc_fnd_logins
          -> WITH NO DATA ;
Query 20210928_074626_00010_rtb78 failed: This connector does not support creating tables with data
```

Druid connector provides globally available [statements](https://trino.io/docs/current/connector/druid.html) like `'CREATE TABLE tab1 AS' `to access data and metadata from Druid database. However, i am experiencing the error mentioned above.

**Comment by hashhar** [comment]
The CREATE TABLE and CREATE TABLE AS are both under `Schema and Table Management` as I can see on this page - https://trino.io/docs/current/language/sql-support.html#schema-and-table-management which isn't listed as supported on the Druid connector docs.

The Druid connector is read-only today since the only way to ingest data into druid is via files or Kafka hence requires an external service and cannot be done directly in Druid if my understanding and knowledge is correct.

**Comment by DwijadasDey** [comment]
Thanks for clearing the doubts. I looked at the page (https://trino.io/docs/current/language/sql-support.html) entirely earlier, overlooking the Druid connector page information(https://trino.io/docs/current/connector/druid.html).
