### ISSUE TITLE
trino-server-rpm keeps old presto lib jars after upgrade

### ISSUE THREAD

**Issue by bdorange** [trinodb/trino#959]
tested while upgrading from 313 to 314, old 313 jars were in the same lib folder `/usr/lib/presto/lib` as the 314 ones.
the rpm was installed using yum under RHEL 7.4.

this caused my kudu connector to fail the presto server startup, after removing the kudu connector the server started but some features from 314 weren't available (although the presto UI showed 314 in the version number).

**Comment by kokosing** [comment]
@bdorange 

In order to debug this issue we need more information:
Can you please list all the files from `/usr/lib/presto` (with `ls -l` to see size and modification date, `md5sum` could be also helpful) that were installed with 313 in your system just before running `rpm -e` command. Then can you please all do the same but just after the upgrade to 314.

Also can you please describe what commands do you use to install, remove and upgrade Presto?

**Comment by hashhar** [comment]
cc: @aalbu @nineinchnick See also https://github.com/trinodb/trino/blob/f600388f74b6af5b71b7445d1a77699412e5b767/core/trino-server-rpm/src/main/rpm/postremove#L12 which might be related.

**Comment by mosabua** [comment]
This has been fixed long ago.
