### ISSUE TITLE
Determine and support appropriate schema evolution semantics for Iceberg table with legacy Hive files

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#9843]
For a Hive table migrated to iceberg with https://iceberg.apache.org/spark-procedures/#migrate-table-procedure 
if I drop a field and add a new field with same name, should i expect nulls, or data from legacy files that do not use field ID mappings?

Currently, the Trino implementation uses current names when reading a legacy file (a file without field ID information), so i will see data being read.
I would expect that legacy files are read with _first_ Iceberg table schema, so i would expect nulls being read from legacy files.

**Comment by findepi** [comment]
cc @rdblue @losipiuk @alexjo2144 @phd3

**Comment by rdblue** [comment]
We solved this problem by using a name mapping that is stored in table properties as `schema.name-mapping.default`. The name mapping is a bit more flexible than using the current field names:
1. It supports multiple names per field, in case the name has changed in the past (Avro field aliases)
2. It is not based on the current schema, so the schema can evolve normally (e.g. rename a field)

I've been debating whether to put this in the spec or to start a secondary optional spec for it. It would be great to hear what people here think.

Using a name mapping is fairly easy. When reading a data file, you check whether the file has any field IDs. If it does, then use those IDs. If not, apply the name mapping using one of the existing utility methods in Iceberg to produce a file schema with field IDs. Then just use that file schema instead of the original.

It's also possible for us to create an ID to ID mapping, but we haven't yet. This would be needed to support formats like Protobuf or Thrift that use different IDs. We could also use it to map from another table's IDs to support moving files from one table to another. Right now, we have no plans to add this but I thought I'd at least outline the idea.

**Comment by findepi** [comment]
Seems like `schema.name-mapping.default` might be addressing problem what's the semantics of a migrated table. Thanks @rdblue for sharing this.
If this is non-spec (currently), what's the specwise behavior for migrated tables after table schema is further evolved?

**Comment by rdblue** [comment]
The spec does not have a special way to support "migrated" data files. Files are required to have correct field IDs. If they have no field IDs, then they have no columns.

The name to ID mapping is only applied when a file has no IDs, so it is used to convert from name-based column resolution into ID-based. Since data files either have IDs or not, schema evolution works just fine for all new data files and for all old data files.

**Comment by rdblue** [comment]
If there is no mapping and no field IDs, then to Iceberg the file has no columns.

**Comment by findepi** [comment]
> then to Iceberg the file has no columns. The Parquet behavior is correct and all Iceberg columns should be null.

from engineering perspective, this sounds logical, but i am concerned about practical implications of such approach.
A file full of data, which we don't attempt to read and return `null`s instead -- this is unlikely user intention, so failing could be a clearer and more useful reaction.
i.e. if something doesn't look like an iceberg file, we should fail to read it in iceberg, _unless_ there is additional information (mapping) indicating how to read non-Iceberg files.

**Comment by rdblue** [comment]
@findepi, failing is also reasonable if you see that a file has no columns.
