### ISSUE TITLE
Not an RPM package. Can symlink.groovy be used to control the size?

### ISSUE THREAD

**Issue by Narcasserun** [trinodb/trino#9880]
If it is not an RPM package but a tar package, how can I use trino-server-rpm/src/main/script/symlink.groovy to control the size?

**Comment by Narcasserun** [comment]
#3399

**Comment by Narcasserun** [comment]
@electrum I need your help sir

**Comment by electrum** [comment]
The tarball uses a hard links, rather than symlinks, to minimize the size. You can see that they are both of similar size:

https://repo1.maven.org/maven2/io/trino/trino-server/364/
https://repo1.maven.org/maven2/io/trino/trino-server-rpm/364/

```
trino-server-364.tar.gz       2021-11-01 21:52     623114003      
trino-server-rpm-364.rpm      2021-11-01 21:56     623255503      
```

The hard linking is done here: https://github.com/trinodb/trino/blob/43e583667e8fbcb23038f932ccd32f5adc7c5c3f/core/trino-server/src/main/provisio/presto.xml#L3

**Comment by Narcasserun** [comment]
> archive name="${project.artifactId}-${project.version}.tar.gz" hardLinkIncludes="**/*.jar" />

thank you，sir
