### ISSUE TITLE
Make Metric(s) parameterized

### ISSUE THREAD

**Issue by ksobolew** [trinodb/trino#9903]
The architecture of the `Metric` and `Metrics` classes is conceptually simple, but hard to implement generically: `Metrics` is just a container of `Metric` instances, but the actual underlying type is generic. The way it currently works is that the `Metrics` class is not parameterized, and `Metric`, which is, is passed around as a raw type. As a result the users of these classes must "know" what underlying type to expect. And since these are raw types, even making everything a `Metric<?>` would be an improvement.

The problem with fixing this, though, is that it may require some rearchitecture of the surrounding code. Among other things, Java generics tend to be "contagious", requiring adding the type parameter to more and more surrounding classes.

**Comment by ksobolew** [comment]
Actually, the only Java code that uses these classes for something are tests - in production code these objects are simply exported via JSON.

**Comment by findepi** [comment]
> Among other things, Java generics tend to be "contagious", requiring adding the type parameter to more and more surrounding classes.


This is precisely why we use things like `List<ColumnHandle>` even though `List<? extends ColumnHandle>` would be more correct. Being "more correct" at the cost of making code harder to read is not a great deal. 

> in production code these objects are simply exported via JSON. 

that sounds like there is no benefit from changing how Metric class is defined.

there is still value from removing use of raw types (or suppressing IDE warning when use of raw type is indispensable). Clearing IDE  warnings is worthwhile since it makes other -- potentially more important -- warnings more visible.

Is this issue about fixing raw type usages around `Metric` and `Metrics` classes, or something else?

**Comment by ksobolew** [comment]
The minimal version would make `io.trino.spi.metrics.Metrics#getMetrics` return something that does not include raw types.

**Comment by findepi** [comment]
Sure:
`public Map<String, Metric> getMetrics()` → `public Map<String, Metric<?>> getMetrics()`

**Comment by ksobolew** [comment]
It's not that easy, because there's the `Accumulator` helper type, which takes the result of `getMetrics()` and needs to merge it with some other `Metrics`. When we have raw `Metric` instances, that's easy, because the actual type is ignored and we rely on throwing `ClassCastException` when they're incompatible, but when it's `Metric<?>` the compiler actually expects us to care. We can cast it back to raw `Metric`, of course, but I would feel dirty doing that ;)
