### ISSUE TITLE
Add DENY permission to grammar and SPI

### ISSUE THREAD

**Issue by dain** [trinodb/trino#9907]
Some security systems support the concept of `DENY` rules.  These are common enough, and I think the impact Trino would be minimal, so I propose we add these.

Proposed grammar is the same as `GRANT` except there is no `WITH GRANT OPTION`.
```
DENY
  (privilege (',' privilege)* | ALL PRIVILEGES)
  ON (SCHEMA | TABLE)? qualifiedName
  TO grantee=principal                                                     #deny 
```

This command would simply be passed through the system like `GRANT` is today.  The expected behavior would be documented in the SPI javadocs as:
* Each triple of entity (schema or table today), privilege, and grantee has a single boolean saying if the privilege is granted or denied.
* An explicit grant overrides a deny, and a deny overrides a grant
* `REVOKE` removes the rule (the grant or deny)

Since information schema is locked down by the ANSI SQL spec, it would continue to only show grants.  A new table would be added to the system schema for the show all permission rules (both grants and denies).

References
* Ranger: https://cwiki.apache.org/confluence/display/RANGER/Deny-conditions+and+excludes+in+Ranger+policies
* SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/statements/deny-transact-sql?view=sql-server-ver15
* Databricks: https://docs.databricks.com/spark/latest/spark-sql/language-manual/security-deny.html

**Comment by ksobolew** [comment]
Regarding semantics, there's a huge issue of overlapping `ALLOW` and `DENY` grants. Usually `DENY` overrides `ALLOW`, so that the system fails closed, unless the latter is more specific. In some systems the ordering of the rules matters (the last applicable one wins, for example). In short, this has to be explicit and carefully specified. I'm not sure, though, if this is a responsibility of the SQL model or the selected security model.

In general I think it makes sense, but one could also imagine a comprehensive system/syntax to manage the security mechanism, of which this only a part. Another would be a way to manage permissions other than the usual CRUD (like `ALTER`, `EXECUTE` etc.), all from SQL. @kokosing do we have plans for something like this? Does it even make sense from out point of view? Perhaps it is best to leave SQL alone and manage the permissions from some kind of UI for the security backend?

**Comment by kokosing** [comment]
I like the syntax. However as @ksobolew pointed out we need to specify the semantics. Is this syntax by any chance covered by ANSI SQL?

> An explicit grant overrides a deny

That would suggest checking what is more specific. If GRANT is more specific than DENY it should override DENY. Like GRANT on `schema1.table1` overrides DENY on `schema1`.

However from what I see in mentioned docs. All Ranger, SQLServer, Databricks do not allow that. They in general follow:

>  DENY can be used to ensure that a user or principal cannot access the specified object, despite any implicit or explicit GRANTs. When an object is accessed, Databricks first checks if there are any explicit or implicit DENYs on the object before checking if there are any explicit or implicit GRANTs.

That model is much easier to reason about.

**Comment by dain** [comment]
> An explicit grant overrides a deny

By this I mean if you execute. `DENY SELECT ON t TO bob` followed by  `GRANT SELECT ON t TO bob` this removes the deny rule and replaces it with the select rule, or said another way, there is only one slot for `SELECT, t, bob` and it can point to `ALLOW` or `DENY`.   Anyway, I'm not suggesting that we "enforce" or "require" a specific security model where deny overrides grants.  @martint suggested we provide some guidance in the SPI javadocs on how someone would use this API, but obviously we have no way to enforce the security system implement this suggested model or any other model.

**Comment by martint** [comment]
The syntax looks good to me. Regarding the semantics, I think it's the only reasonable way to do it, and there's precedent from other databases like SQL server. Trying to keep grant and deny rules active at the same time is more confusing -- does a deny imply the revocation of a grant and viceversa? How would one revoke a deny given that REVOKE only considers grants, today? What does it even mean to revoke a deny?

**Comment by dain** [comment]
Implemented in https://github.com/trinodb/trino/pull/10205
