### ISSUE TITLE
Feature request: Support for jdbc catalog in Iceberg Connector

### ISSUE THREAD

**Issue by racevedoo** [trinodb/trino#9968]
Would be great if trino supported jdbc catalog in iceberg connector

**Comment by csimplestring** [comment]
+1 
If jdbc catalog for Iceberg is supported, then no need to use hive metastore, which makes it way easier to use.

**Comment by racevedoo** [comment]
> +1 If jdbc catalog for Iceberg is supported, then no need to use hive metastore, which makes it way easier to use.

definitely!

**Comment by Arnonrgo** [comment]
Hi - has this been abandoned?

**Comment by jebnix** [comment]
@Arnonrgo No. @ebyhr has rebased https://github.com/trinodb/trino/pull/11772 to resolve conflicts. Hope we'll see this one get merged soon. Well anticipated

**Comment by ebyhr** [comment]
`@issue-subscriber` We lean toward to canceling JDBC catalog because REST catalog that enables accessing JDBC catalog was already merged recently. This is not a final decision. Please let us know if JDBC catalog support is still required. We're glad if you can share why a direct JDBC catalog without REST catalog is necessary in your use case.

**Comment by ebyhr** [comment]
@almogtavor @jebnix @kingbrown9 @lynch19 I found you react with emoji. Please be more verbal. We would like to hear use-cases from the community. Thumbs-down doesn't explain anything about it.

**Comment by jebnix** [comment]
@ebyhr I think there is no reason to give up on this great PR and work that have already been invested on this super anticipated feature (top 5 most liked and commented issues of Trino), just because of temporary time management issues. I don’t want to get involved with how the Trino developers time get managed, of course. But regarding the overhead of the REST Catalog I have to agree. That’s a pretty serious overhead to give to teams that just want to set up and maintain Trino for the Iceberg usage. The REST Catalog is much better than Hive metastore, but that’s still redundant overhead comparing to JDBC. A JDBC catalog is necessary because of the simplicity and support it has. The REST catalog is quite new, and I can see any situation where people would stop asking for the JDBC catalog, since it’s so ideal. From what it looks like, there is about of 80-90% of the work done. I don’t see any reason for it to get dropped. I agree that the Helm stuff is super important, but I’m not at the decision making position anyway. Will the JDBC get used? A lot.
